classdef DeadTime < rietveld.func.spec.corr.DeadTimeInterface
	
	methods (Access = public)
		
		function X = execute(obj, X, general, meas, phase, spec)
			
% 			deltaE = obj.sfwc.DeltaEDeadTime.execute([], general, meas, phase, spec);

% 			X = X - deltaE;
		end
		
		function obj = addFunctionParameters(obj, pc) %#ok
% 			
% 			obj.addParameter(pc, 'DeadTime',...
% 				'Category', 'Measurement',...
% 				'ParamSize', [1, 1],...
% 				'Constant', true,...
% 				'PhaseDep', false,...
% 				'SpecDep', true);
% 			obj.addParameter(pc, 'LowerChannelBound',...
% 				'Category', 'Measurement',...
% 				'ParamSize', [1, 1],...
% 				'Constant', true,...
% 				'PhaseDep', false,...
% 				'SpecDep', false);
% 			obj.addParameter(pc, 'UpperChannelBound',...
% 				'Category', 'Measurement',...
% 				'ParamSize', [1, 1],...
% 				'Constant', true,...
% 				'PhaseDep', false,...
% 				'SpecDep', false);
% 			obj.addParameter(pc, 'FluorChannelPositions',...
% 				'Category', 'Measurement',...
% 				'ParamSize', [NaN, 2],...
% 				'Constant', true,...
% 				'PhaseDep', false,...
% 				'SpecDep', false,...
% 				'Value',[1 1]);
		end		
	end
	
	methods (Access = protected)
		
		function obj = initSubFunctions(obj)
% 			obj.addSubFunction('DeltaEDeadTime', 'rietveld.func.spec.corr.DeltaEDeadTime', rietveld.func.spec.corr.DeltaEDeadTime());
		end
	end	
end

