function CreatDiffGUI()
h.CreateDiffractometer = figure('Name','Create Diffractometer','MenuBar','none','ToolBar','none','NumberTitle','off','Tag','CreateDiff','Position', [25 50 1250 550]);
% assignin('base', 'mydata', h.myfig);
% set (gcf, 'units', 'normalized', 'outerposition', [0.1 0.1 .759 .795]);
set (gcf, 'units', 'normalized', 'outerposition', [0.1 0.1 .759 .78]);
% set (gcf, 'WindowButtonMotionFcn', @mouseMove);
% set (gcf, 'units', 'normalized', 'outerposition', [0 0 1 1]);
% MaximizeFigureWindow
s = warning('off', 'MATLAB:uitabgroup:OldVersion');
h.TabGroup = uitabgroup('Parent',h.CreateDiffractometer,'units', 'normalized');
h.Tabs(1) = uitab('Parent',h.TabGroup, 'Title','Create diffractometer');
h.CreateDiffpanel = uipanel( ...
'Parent', h.Tabs(1),...
'Units', 'Normalized', ...
'Position', [0.0025 0.0025 0.996 0.995], ...
'Title', 'Create diffractometer file' ...
);

h.textelementDiff1 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.003 0.955 0.175 0.04] ,...
'HorizontalAlignment', 'left', ...
'String', 'Load measurement file from which a new diffactometer file should be created. The file and scan headers must conform to some formatting. A sample file is included with the program.' ...
);

% Create graphic objects in "Create diffractometer" Panel
% Edit field that shows the current measurement file
h.selectfilename = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.003 0.925 0.125 0.025], ...
'Tag', 'selectfilename', ...
'Enable', 'on', ...
'String', 'Select measurement file...' ...
);
% Open button in order to load the measurement file
h.openbutton1 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.135 0.925 0.04 0.025], ...
'String', 'Open', ...
'Tag', 'Loadbutton1', ...
'Callback', {@OpenFileCallback} ...
);

%% Listbox that shows the first 30 lines of the file loaded
% Title of listbox
h.titlelistbox1 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'FontWeight', 'bold' ,...
'Position', [0.003 0.89 0.2 0.02] ,...
'HorizontalAlignment', 'left', ...
'String', 'Preview of the first 50 lines of the measurement file' ...
);
% Listbox for preview of file header
h.PeviewFileHeaderListBox = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'listbox', ...
'Units', 'Normalized', ...
'Position', [0.003 0.652 0.4 0.24], ...
'String', '-- Preview of the first 50 lines of the measurement file will be shown here --', ...
'Tag', 'PeviewFileHeaderListBox', ...
'Enable', 'inactive' ...
);

% Title for input of file header literals
h.textliteralsfileheader1 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'FontWeight', 'bold' ,...
'Position', [0.003 0.625 0.2 0.02] ,...
'HorizontalAlignment', 'left', ...
'String', 'Define literals for import of file header and single scan' ...
);

% Define literals for import of last line of file header
h.defineLastLineHeader = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.065 0.6 0.045 0.025], ...
'Tag', 'defineLastLineHeader', ...
'Enable', 'on', ...
'String', '#C' ...
);

h.textLastLineHeader = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.005 0.6 0.0565 0.02] ,...
'HorizontalAlignment', 'left', ...
'String', 'Last line of file header' ...
);

% OK button for import of file header
h.importFileHeader = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.115 0.6 0.05 0.025], ...
'String', 'Import file header', ...
'Tag', 'importmotornames', ...
'Callback', {@importfileheader} ...
);

% Define scan name literal
h.defineScanName = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.2025 0.6 0.045 0.025], ...
'Tag', 'defineScanName', ...
'Enable', 'on', ...
'String', '#S' ...
);

h.textScanName = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.17 0.6 0.03 0.02] ,...
'HorizontalAlignment', 'left', ...
'String', 'Scan name' ...
);

% Define last line of scan header
h.defineLastLineScanHeader = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.3075 0.6 0.04 0.025], ...
'Tag', 'defineLastLineScanHeader', ...
'Enable', 'on', ...
'String', '' ...
);

h.textLastLineScanHeader = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.25 0.6 0.055 0.02] ,...
'HorizontalAlignment', 'left', ...
'String', 'Last line scan header' ...
);

% OK button for import of scan
h.importScan = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.35125 0.6 0.0525 0.025], ...
'String', 'Import single scan', ...
'Tag', 'importscan', ...
'Callback', {@importscan} ...
);

% Title of file header listbox
h.titlefileheaderlistbox1 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'FontWeight', 'bold' ,...
'Position', [0.003 0.57 0.2 0.02] ,...
'HorizontalAlignment', 'left', ...
'String', 'File header' ...
);

h.FileHeaderListBox = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'listbox', ...
'Units', 'Normalized', ...
'Position', [0.003 0.42 0.4 0.15], ...
'String', '-- File header wil be shown here. Define the correct literal first. --', ...
'Tag', 'FileHeaderListBox', ...
'Enable', 'inactive' ...
);

% Title of listbox
h.titlelistbox2 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'FontWeight', 'bold' ,...
'Position', [0.003 0.39 0.2 0.02] ,...
'HorizontalAlignment', 'left', ...
'String', 'Preview of a single scan of the measurement file' ...
);

h.ScanHeaderListBox = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'listbox', ...
'Units', 'Normalized', ...
'Position', [0.003 0.01 0.4 0.379], ...
'String', '-- Single scan will be shown here. Define the correct literal first. --', ...
'Tag', 'ScanHeaderEditField', ...
'Enable', 'inactive' ...
);


% Create table where the user can define the motor name literals, in case
% they are not listed properly.
% Data for empty table
tabledata1 = cell(20,1);
tabledata2 = cell(20,1);
tabledata3 = cell(20,1);

% Default value for popup menu
tabledata1(:) = {'       enter name'};
tabledata2(:) = {'            define literal'};
tabledata3(:) = {'     1'};

% Create table for user defined motor names
h.tabledefinemotornames = uitable('Parent', h.CreateDiffpanel, ...
'Units', 'Normalized', ...
'Position', [0.425 0.738 0.164 0.154], ...
'ColumnWidth', {100 130 40}, ...
'ColumnName', {'Motor name' 'Literal motor' 'Value'} ,...
'ColumnFormat',({char char char}), ...
'ColumnEditable',[true true true], ...
'Data',[tabledata1 tabledata2 tabledata3]);

% Preview button for export of motor names
h.previewmotors = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.6 0.865 0.071 0.025], ...
'String', 'Preview defined motors', ...
'Tag', 'previewmotors', ...
'Callback', {@previewmotors} ...
);

% Create table for preview of user defined motors
h.tableuserdefinedmotors = uitable('Parent', h.CreateDiffpanel, ...
'Units', 'Normalized', ...
'Position', [0.68 0.738 0.118 0.154], ...
'ColumnWidth', {100 80}, ...
'ColumnName', {'Motor name' 'Value'} ,...
'ColumnFormat',({char char}), ...
'ColumnEditable',[false false], ...
'Data',[tabledata1 tabledata3]);

% Save button for export of motor names
h.savemotornames = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.6 0.83 0.06 0.025], ...
'String', 'Save motor names', ...
'Tag', 'savemotornames', ...
'Callback', {@savemotornames} ...
);

% Title for input of file header literals
h.textliteralsfileheader1 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'FontWeight', 'bold' ,...
'Position', [0.425 0.705 0.4 0.02] ,...
'HorizontalAlignment', 'left', ...
'String', 'Define literal and format for import of file and scan header lines from files not recorded with SPEC' ...
);

% Define file name literal
h.textliteralsamplename = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.43 0.68 0.025 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'File name' ...
);

h.defineSampleNameLiteral = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.4575 0.68 0.04 0.025], ...
'Tag', 'defineSampleNameLiteral', ...
'Enable', 'on', ...
'String', '#F' ...
);

h.defineSampleNameFormat = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.5025 0.68 0.1 0.025], ...
'Tag', 'defineSampleNameFormat', ...
'Enable', 'on', ...
'String', '#F %s' ...
);

% Preview button for file name
h.previewbuttonfilename = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.6075 0.68 0.035 0.025], ...
'String', 'Preview', ...
'Tag', 'previewbuttonfilename', ...
'Callback', {@previewbuttoncallback} ...
);

h.previewfilename = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.6475 0.68 0.15 0.025], ...
'Tag', 'previewfilename', ...
'Enable', 'on', ...
'String', '' ...
);

% Define Channel literal
h.textliteralchannelstart = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.425 0.65 0.03 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', '1st Channel' ...
);

h.defineChannelStart = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.4575 0.65 0.04 0.025], ...
'Tag', 'defineChannelStart', ...
'Enable', 'on', ...
'String', '#Start' ...
);

h.defineChannelStartvalue = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.5025 0.65 0.1 0.025], ...
'Tag', 'defineChannelStartvalue', ...
'Enable', 'on', ...
'String', '1' ...
);

% Preview button for 1st channel
h.previewbuttonchannelstart = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.6075 0.65 0.035 0.025], ...
'String', 'Preview', ...
'Tag', 'previewbuttonchannelstart', ...
'Callback', {@previewbuttoncallback} ...
);

h.previewchannelstart = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.6475 0.65 0.15 0.025], ...
'Tag', 'previewchannelstart', ...
'Enable', 'on', ...
'String', '' ...
);

h.textliteralchannelend = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.42 0.62 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'Last Channel' ...
);

h.defineChannelEnd = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.4575 0.62 0.04 0.025], ...
'Tag', 'defineChannelEnd', ...
'Enable', 'on', ...
'String', '#End' ...
);

h.defineChannelEndvalue = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.5025 0.62 0.1 0.025], ...
'Tag', 'defineChannelEndvalue', ...
'Enable', 'on', ...
'String', '1' ...
);

% Preview button for last channel
h.previewbuttonchannelend = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.6075 0.62 0.035 0.025], ...
'String', 'Preview', ...
'Tag', 'previewbuttonchannelend', ...
'Callback', {@previewbuttoncallback} ...
);

h.previewchannelend = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.6475 0.62 0.15 0.025], ...
'Tag', 'previewchannelend', ...
'Enable', 'on', ...
'String', '' ...
);

% Title for input of file header literals
h.textliteralsfileheader2 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'FontWeight', 'bold' ,...
'Position', [0.425 0.53 0.4 0.02] ,...
'HorizontalAlignment', 'left', ...
'String', 'Define literal and format for import of file and scan header lines from files recorded with SPEC' ...
);

% Define literal for SPEC file name
h.textliteralsSPECFilename = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.42 0.5 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'File name' ...
);

h.defineliteralSPECFilenames = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.4575 0.5 0.04 0.025], ...
'Tag', 'defineliteralSPECFilenames', ...
'Enable', 'on', ...
'String', '#F' ...
);

h.defineFormatSPECFilename = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.5025 0.5 0.1 0.025], ...
'Tag', 'defineFormatSPECFilename', ...
'Enable', 'on', ...
'String', '#F %*[^/]/%*[^/]/%[^.]' ...
);

% Preview button for file name
h.previewbuttonSPECfilename = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.6075 0.5 0.035 0.025], ...
'String', 'Preview', ...
'Tag', 'previewbuttonSPECfilename', ...
'Callback', {@previewbuttoncallback} ...
);

h.previewSPECfilename = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.6475 0.5 0.15 0.025], ...
'Tag', 'previewSPECfilename', ...
'Enable', 'on', ...
'String', '' ...
);

% Define literal for SPEC motor names
h.textliteralsSPECMotorname = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.42 0.47 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'Motor names' ...
);

h.defineliteralSPECMotornames = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.4575 0.47 0.04 0.025], ...
'Tag', 'defineliteralSPECMotornames', ...
'Enable', 'on', ...
'String', '#O' ...
);

h.textliteralsSPECMotorValues = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.42 0.44 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'Motor values' ...
);

h.defineliteralSPECMotorValues = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.4575 0.44 0.04 0.025], ...
'Tag', 'defineliteralSPECMotorValues', ...
'Enable', 'on', ...
'String', '#P' ...
);

h.textliteralsSPECChannels = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.42 0.41 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'Channels' ...
);

h.defineliteralSPECChannels = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.4575 0.41 0.04 0.025], ...
'Tag', 'defineliteralSPECChannels', ...
'Enable', 'on', ...
'String', '#@CHANN' ...
);

h.textliteralsSPECIntensities = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.5025 0.47 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'Intensities' ...
);

h.defineliteralSPECIntensities = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.54 0.47 0.04 0.025], ...
'Tag', 'defineliteralSPECIntensities', ...
'Enable', 'on', ...
'String', '@A' ...
);

h.textliteralsSPECDate = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.5025 0.44 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'Date' ...
);

h.defineliteralSPECDate = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.54 0.44 0.04 0.025], ...
'Tag', 'defineliteralSPECDate', ...
'Enable', 'on', ...
'String', '#D' ...
);

h.textliteralsSPECTimes = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.5025 0.41 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'Times' ...
);

h.defineliteralSPECTimes = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.54 0.41 0.04 0.025], ...
'Tag', 'defineliteralSPECTimes', ...
'Enable', 'on', ...
'String', '#@CTIME' ...
);

h.textliteralsSPECNumDet = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.585 0.47 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'Detectors' ...
);

h.defineliteralSPECNumDet = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.6225 0.47 0.04 0.025], ...
'Tag', 'defineliteralSPECFilenames', ...
'Enable', 'on', ...
'String', '#@MCADEV' ...
);

h.textliteralsSPECTemp = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.585 0.44 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'Temperature' ...
);

h.defineliteralSPECTemp = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.6225 0.44 0.04 0.025], ...
'Tag', 'defineliteralSPECTemp', ...
'Enable', 'on', ...
'String', '#@TEMP' ...
);

h.textliteralsSPECRingCurrent = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.585 0.41 0.035 0.02] ,...
'HorizontalAlignment', 'right', ...
'String', 'RingCurrent' ...
);

h.defineliteralSPECRingCurrent = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.6225 0.41 0.04 0.025], ...
'Tag', 'defineliteralSPECRingCurrent', ...
'Enable', 'on', ...
'String', '#@RC' ...
);


% Text explaining how the user can create the diffractometer
h.textelementDiff1 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.425 0.2825 0.3 0.04] ,...
'HorizontalAlignment', 'left', ...
'Background', 'w',...
'String', 'Load motor names from file header. Then select the appropriate positioner from the drop down menu in order to assign the motors to the new diffractometer file.' ...
);

% Import button for import of motor names
h.importmotornames = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.7925 0.29 0.06 0.025], ...
'String', 'Import motor names', ...
'Tag', 'importmotornames', ...
'Callback', {@importmotornames} ...
);

h.checkboxSelectFileFormat = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'checkbox', ...
'Units', 'Normalized', ...
'Position', [0.7475 0.2925 0.0425 0.02], ...
'Tag', 'checkboxSelectFileFormat', ...
'String', 'SPEC format', ...
'Value', 1 ...
);

% Default table data for motor names
datastring = {'    motor name'};
tabledata = repmat(datastring,8,1);
popupmenudata = cell(size(tabledata,1),1);

% Default value for popup menu
popupmenudata(:) = {'choose positioner'};

% Create table for motor names
h.tablemotornames = uitable('Parent', h.CreateDiffpanel, ...
'Units', 'Normalized', ...
'Position', [0.425 0.12 0.42805 0.155], ...
'Rowname', [],...
'ColumnWidth', {80 130 80 130 80 130 80 130}, ...
'ColumnName', {'Motor' 'Positioner' 'Motor' 'Positioner' 'Motor' 'Positioner' 'Motor' 'Positioner'} ,...
'ColumnFormat',({char {'choose positioner' 'Sample Positioner' 'Detector Positioner' 'Source Positioner'} ...
                char {'choose positioner' 'Sample Positioner' 'Detector Positioner' 'Source Positioner'} ...
                char {'choose positioner' 'Sample Positioner' 'Detector Positioner' 'Source Positioner'} ...
                char {'choose positioner' 'Sample Positioner' 'Detector Positioner' 'Source Positioner'}}), ...
'ColumnEditable',[false true false true false true false true], ...
'Data',[tabledata popupmenudata tabledata popupmenudata tabledata popupmenudata tabledata popupmenudata]);
% Pos 4 Reihen: [0.425 0.12 0.33805 0.155]
% Pos 3 Reihen: [0.425 0.12 0.24 0.155]
% Pos 2 Reihen: [0.425 0.12 0.214 0.155]
% ColumnFormat: eine Zeile wurde gelöscht, scheint zu viel gewesen zu sein

% % Create table for motor names
% h.tablemotornames = uitable('Parent', h.CreateDiffpanel, ...
% 'Units', 'Normalized', ...
% 'Position', [0.003 0.12 0.3365 0.155], ...
% 'ColumnWidth', {80 130 80 130 80 130 80 130}, ...
% 'ColumnName', {'Motor' 'Positioner' 'Motor' 'Positioner' 'Motor' 'Positioner' 'Motor' 'Positioner'} ,...
% 'ColumnFormat',({char {'choose positioner' 'Sample Positioner' 'Detector Positioner' 'Source Positioner'} ...
%                 char {'choose positioner' 'Sample Positioner' 'Detector Positioner' 'Source Positioner'} ...
%                 char {'choose positioner' 'Sample Positioner' 'Detector Positioner' 'Source Positioner'} ...
%                 char {'choose positioner' 'Sample Positioner' 'Detector Positioner' 'Source Positioner'}}), ...
% 'ColumnEditable',[false true false true false true false true], ...
% 'Data',[tabledata popupmenudata tabledata popupmenudata tabledata popupmenudata tabledata popupmenudata]);


% Select motors that account for the requiered motors for stress analysis
% Default table data for motor names
tabledata1 = {'  omega' '  tth' '  phi' '  psi' '  x' '  y' '  z'}';
popupmenudata = cell(size(tabledata1,1),1);

% Default value for popup menu
popupmenudata(:) = {'choose motor'};

% Create table for motor names
h.tablevirtualmotors = uitable('Parent', h.CreateDiffpanel, ...
'Units', 'Normalized', ...
'Position', [0.425 0.01 0.1585 0.0875], ...
'ColumnWidth', {120 160}, ...
'ColumnName', {'Motor EDDIDAT' 'Motor diffractometer'} ,...
'ColumnFormat',({char {'choose motor' 'motor1' 'motor2' 'motor3'}}), ...
'ColumnEditable',[false true], ...
'CellEditCallback',{@updatetableusermotordata}, ...
'Data',[tabledata1 popupmenudata]);

% Text explaining how the user can create the diffractometer
h.textelementDiff2 = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'text', ...
'Units', 'Normalized', ...
'Position', [0.595 0.05 0.17 0.04] ,...
'HorizontalAlignment', 'left', ...
'String', 'Assign the internal motors of EDDIDAT to the corresponding motors of the new diffractometer. Then select a name for the diffractometer and create the new diffractometer file.' ...
);

% Edit field to enter the diffractometer name
h.enterdifffilename = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'edit', ...
'Units', 'Normalized', ...
'Position', [0.595 0.01 0.1 0.025], ...
'Tag', 'enterdifffilename', ...
'Enable', 'inactive', ...
'String', 'Enter name for diffractometer', ...
'ButtonDownFcn', {@clearbuttondown} ...
);

% Create diffractometer button
h.creatediffractometer = uicontrol( ...
'Parent', h.CreateDiffpanel, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.7025 0.01 0.06 0.025], ...
'String', 'Create diffractometer', ...
'Tag', 'creatediffractometer', ...
'Callback', {@creatediffractometer} ...
);


guidata(h.CreateDiffractometer, h);

function OpenFileCallback(hObj,~)
% Callback for "Open File" pushbutton
h = guidata(hObj);

% h = handles;
% Open file dialog box - Folder may have to be changed manually
[FileName,FilePath]  = uigetfile('*.*','Load measurement file',[General.ProgramInfo.Path,'\Data\Measurements\']);

if FileName == 0
  % user pressed cancel
  return
end

Path = fullfile(FilePath, FileName);
h.MeasFile = Tools.StringOperations.AsciiFile2Text(Path,'\r\n');

% assignin('base','M',h.MeasFile)

% Read first 50 lines from file header and write to listbox
for i_c = 1:50
    HeaderLines{i_c,:} = h.MeasFile(i_c,1:end);
end

set(h.PeviewFileHeaderListBox,'string',string(HeaderLines))

ExPath = fullfile(FilePath, FileName);
% Set FileName to string and ExPath to UserData of Edit-Field
set(h.selectfilename,'string',FileName)
set(h.selectfilename,'UserData',ExPath)

guidata(hObj, h);

function importfileheader(hObj,~)
% Callback for import of file header
h = guidata(hObj);

LastLineHeader = get(h.defineLastLineHeader,'String');

Index_tmp = Tools.StringOperations.SearchString(h.MeasFile, LastLineHeader);

for i_c = 1:Index_tmp(end,1)
    FileHeaderLines{i_c,:} = h.MeasFile(i_c,1:end);
end

set(h.FileHeaderListBox,'string',string(FileHeaderLines))

guidata(hObj, h);

function importscan(hObj,~)
% Callback for import of file header
h = guidata(hObj);

Literal = get(h.defineScanName,'String');
%Indizies des Scanliterals
Index_Scan = Tools.StringOperations.SearchString(h.MeasFile, Literal);
% %Indizies der Leerzeilen
% Index_BlankLines = Tools.StringOperations.SearchBlankLines(h.MeasFile);
% %--> Imaginäre Leerzeile am Ende des MessFiles einfügen
% if Index_BlankLines(end) ~= size(h.MeasFile,1)
%     Index_BlankLines(end+1) = size(h.MeasFile,1) + 1;
% end

if size(Index_Scan,1) < 2
%     Index_NextBlankLine = find(Index_BlankLines > Index_Scan(1),1,'first');
%     ScanLines = h.MeasFile(Index_Scan(i_c):Index_BlankLines(Index_NextBlankLine)-1,:);
    ScanLines = h.MeasFile(Index_Scan(1):end,:);
else
    ScanLines = h.MeasFile(Index_Scan(1):Index_Scan(2)-1,:);
end

set(h.ScanHeaderListBox,'string',string(ScanLines))

guidata(hObj, h);

function savemotornames(hObj,~)
% Callback for import of motor names
h = guidata(hObj);

% get motor names defined by the user
motordata = get(h.tabledefinemotornames, 'data');

% Find arrays that contain motor names defined by user
Index = find(contains(motordata,'enter name'));
% Delete empty cells
motordata(Index,:) = [];
% Create structure with motors and corresponding literal
for k = 1 : size(motordata,1)
    h.UserMotors.(motordata{k,1}) = motordata{k,2};  % Assign index to s.fred, s.sam, and s.al
end
% Access motor structure
h.LiteralsUser = struct2cell(h.UserMotors);
h.MotorNamesUser = fieldnames(h.UserMotors);
% assignin('base','MotorNamesUser',h.MotorNamesUser)
% assignin('base','LiteralsUser',h.LiteralsUser)
% Extract single scan header for search of motors
LastLineFileHeader = get(h.defineLastLineHeader,'String');
IndexLastLineFileHeader = Tools.StringOperations.SearchString(h.MeasFile,LastLineFileHeader);
LastLineScanHeader = get(h.defineLastLineScanHeader,'String');
IndexLastScanHeader = Tools.StringOperations.SearchString(h.MeasFile,LastLineScanHeader);

h.ScanHeader = h.MeasFile(IndexLastLineFileHeader:IndexLastScanHeader(1),:);

% Search scan for literals
for k = 1:length(h.LiteralsUser)
    Index_tmp(k,:) = Tools.StringOperations.SearchString(h.ScanHeader,h.LiteralsUser{k});
end

% Find values for motors
for k = 1:length(Index_tmp)
    h.MotorValue(k,:) = extractNumFromStr(h.ScanHeader(Index_tmp(k,1),Index_tmp(k,2):end));
end

guidata(hObj, h);

function previewbuttoncallback(hObj,~)
% Callback for import of motor names
h = guidata(hObj);

% Check which button was pushed 
if strcmp(get(hObj,'tag'),get(h.previewbuttonfilename,'tag'))
    LiteralFileName = get(h.defineSampleNameLiteral,'String');
    FormatFileName = get(h.defineSampleNameFormat,'String');
    Index_tmp = Tools.StringOperations.SearchString(h.MeasFile,LiteralFileName);
    MeasurementSeries = sscanf(h.MeasFile(Index_tmp(1),:),FormatFileName);
    if isempty(MeasurementSeries)
        set(h.previewfilename,'str','Wrong format. Please check.')
    else
        set(h.previewfilename,'str',MeasurementSeries)
    end
elseif strcmp(get(hObj,'tag'),get(h.previewbuttonchannelstart,'tag'))
    LiteralFileName = get(h.defineChannelStart,'String');
    ValueUser = get(h.defineChannelStartvalue,'String');
    Index_tmp = Tools.StringOperations.SearchString(h.MeasFile,LiteralFileName);
    Value = extractNumFromStr(h.MeasFile(Index_tmp(1),Index_tmp(2):end));
    if isempty(Value)
        set(h.previewchannelstart,'str','Wrong format. Please check.')
    else
        set(h.previewchannelstart,'str',Value(str2double(ValueUser)))
    end
elseif strcmp(get(hObj,'tag'),get(h.previewbuttonchannelend,'tag'))
    LiteralFileName = get(h.defineChannelEnd,'String');
    ValueUser = get(h.defineChannelEndvalue,'String');
    Index_tmp = Tools.StringOperations.SearchString(h.MeasFile,LiteralFileName);
    Value = extractNumFromStr(h.MeasFile(Index_tmp(1),Index_tmp(2):end));
    if isempty(Value)
        set(h.previewchannelend,'str','Wrong format. Please check.')
    else
        set(h.previewchannelend,'str',Value(str2double(ValueUser)))
    end
elseif strcmp(get(hObj,'tag'),get(h.previewbuttonSPECfilename,'tag'))
    LiteralFileName = get(h.defineliteralSPECFilenames,'String');
    FormatFileName = get(h.defineFormatSPECFilename,'String');
    Index_tmp = Tools.StringOperations.SearchString(h.MeasFile,LiteralFileName);
    MeasurementSeries = sscanf(h.MeasFile(Index_tmp(1),:),FormatFileName);
    if isempty(MeasurementSeries)
        set(h.previewSPECfilename,'str','Wrong format. Please check.')
    else
        set(h.previewSPECfilename,'str',MeasurementSeries)
    end 
end

guidata(hObj, h);

function previewmotors(hObj,~)
% Callback for import of motor names
h = guidata(hObj);

% get motor names defined by the user
motordata = get(h.tabledefinemotornames, 'data');

% Find arrays that contain motor names defined by user
Index = find(contains(motordata,'enter name'));
% Delete empty cells
motordata(Index,:) = [];
% Create structure with motors and corresponding literal
for k = 1 : size(motordata,1)
    UserMotors.(motordata{k,1}) = motordata{k,2};  % Assign index to s.fred, s.sam, and s.al
end
% Access motor structure
Literals = struct2cell(UserMotors);
% assignin('base','LiteralsETA',Literals)
MotorNames = fieldnames(UserMotors);
% Extract single scan header for search of motors
LastLineFileHeader = get(h.defineLastLineHeader,'String');
IndexLastLineFileHeader = Tools.StringOperations.SearchString(h.MeasFile,LastLineFileHeader);
LastLineScanHeader = get(h.defineLastLineScanHeader,'String');
IndexLastScanHeader = Tools.StringOperations.SearchString(h.MeasFile,LastLineScanHeader);

ScanHeader = h.MeasFile(IndexLastLineFileHeader:IndexLastScanHeader(1),:);
% assignin('base','ScanHeaderETA',ScanHeader)
% Search scan for literals
for k = 1:size(Literals,1)
    Index_tmp(k,:) = Tools.StringOperations.SearchString(ScanHeader,Literals{k});
end

% Find values for motors
for k = 1:length(Index_tmp)
    MotorValue(k,:) = extractNumFromStr(ScanHeader(Index_tmp(k,1),Index_tmp(k,2):end));
end

% Write motor values to file
% Hier fehlt noch der loop für die scans
for k_c = 1:length(Index_tmp)
    Motors_all.(MotorNames{k_c}) = MotorValue(k_c,1);
end

% Get diffractometer motor names
usermotorspreview = [fieldnames(Motors_all),struct2cell(Motors_all)];

set(h.tableuserdefinedmotors,'data',usermotorspreview)
% set(h.tablevirtualmotors, 'ColumnFormat',{char ['choose motor'; usermotorspreview]'})
guidata(hObj, h);
% assignin('base','motordata',motordata)

function importmotornames(hObj,~)
% Callback for import of motor names
h = guidata(hObj);

% Checkbox whether file format is SPEC format or user defined
% SPEC format = 1
FormatCheck = get(h.checkboxSelectFileFormat,'Value');
if FormatCheck == 1
    % Get literal for motors from edit field
    LiteralMotors = get(h.defineliteralSPECMotornames,'String');

    % Find motor names
    Index_tmp = Tools.StringOperations.SearchString(h.MeasFile,LiteralMotors);
    %Prealloc, jede Zeile enthält die Motornamen
    h.MotorNames = cell(size(Index_tmp,1),1);
    %--> Scannen aller Zeilen
    for i_c = 1:size(Index_tmp,1)
        h.MotorNames{i_c} = Tools.StringOperations.ScanWords(...
        h.MeasFile(Index_tmp(i_c),4:end));
    end
else
    % Get user defined motor names
    h.MotorNames = h.MotorNamesUser';
end
% assignin('base','MotorNames',h.MotorNames)
% Table data
motortabledata_tmp = h.MotorNames';
if size(motortabledata_tmp,2) ~= 1
    % Make cell arrays the same length
    maxlen = max(cellfun(@numel, motortabledata_tmp));
    motortabledata = cellfun(@(s) [s, repmat({''}, 1, maxlen - numel(s))], motortabledata_tmp, 'UniformOutput', false);

    % Create drop down 
    modedata = cell(maxlen,1);
    modedata(:) = {'choose motor'};
else
    % Create drop down
    if size(motortabledata_tmp,1) == 1
        motortabledata = motortabledata_tmp';
    else
        motortabledata = motortabledata_tmp;
    end
    modedata = cell(size(motortabledata,1),1);
    modedata(:) = {'choose positioner'};
end
% assignin('base','modedata',modedata)
% assignin('base','motortabledataETA',motortabledata)
% Set table data
if size(motortabledata,2) == 1
    set(h.tablemotornames, 'data',[motortabledata modedata])
    set(h.tablemotornames, 'Position',[0.425 0.12 0.10775 0.155])
    set(h.tablemotornames, 'ColumnWidth',{80 130 80 130 80 130})
    set(h.tablemotornames, 'ColumnName',{'Motor' 'Positioner'})
    set(h.tablemotornames, 'ColumnEditable',[false true])
    % Set virtual motor table data
    % Get diffractometer motor names
    diffmotors = h.MotorNames';
elseif size(motortabledata,2) == 2
    set(h.tablemotornames, 'data',[motortabledata{1}' modedata motortabledata{2}' modedata])
    set(h.tablemotornames, 'Position',[0.425 0.12 0.214 0.155])
    set(h.tablemotornames, 'ColumnWidth',{80 130 80 130 80 130})
    set(h.tablemotornames, 'ColumnName',{'Motor' 'Positioner' 'Motor' 'Positioner'})
    set(h.tablemotornames, 'ColumnEditable',[false true false true])    
    diffmotors = [h.MotorNames{1}';h.MotorNames{2}'];
elseif size(motortabledata,2) == 3
    set(h.tablemotornames, 'data',[motortabledata{1}' modedata motortabledata{2}' modedata motortabledata{3}' modedata])
    set(h.tablemotornames, 'Position',[0.425 0.12 0.321 0.155])
    set(h.tablemotornames, 'ColumnWidth',{80 130 80 130 80 130})
    set(h.tablemotornames, 'ColumnName',{'Motor' 'Positioner' 'Motor' 'Positioner' 'Motor' 'Positioner'})
    set(h.tablemotornames, 'ColumnEditable',[false true false true false true])
    diffmotors = [h.MotorNames{1}';h.MotorNames{2}';h.MotorNames{3}'];
elseif size(motortabledata,2) == 4
    set(h.tablemotornames, 'data',[motortabledata{1}' modedata motortabledata{2}' modedata motortabledata{3}' modedata motortabledata{4}' modedata])
    set(h.tablemotornames, 'Position',[0.425 0.12 0.41905 0.155])
    set(h.tablemotornames, 'ColumnWidth',{80 130 80 130 80 130 80 130})
    set(h.tablemotornames, 'ColumnName',{'Motor' 'Positioner' 'Motor' 'Positioner' 'Motor' 'Positioner ' 'Motor' 'Positioner'})
    set(h.tablemotornames, 'ColumnEditable',[false true false true false true false true])
    diffmotors = [h.MotorNames{1}';h.MotorNames{2}';h.MotorNames{3}';h.MotorNames{3}'];
% elseif size(motortabledata,2) == 5
%     set(h.tablemotornames, 'data',[motortabledata{1}' modedata motortabledata{2}' modedata motortabledata{3}' modedata motortabledata{4}' modedata motortabledata{5}' modedata])
%     set(h.tablemotornames, 'ColumnWidth',{80 130 80 130 80 130 80 130 80 130})
%     set(h.tablemotornames, 'ColumnName',{'Motor' 'Positioner' 'Motor' 'Positioner' 'Motor' 'Positioner' 'Motor' 'Positioner' 'Motor' 'Positioner'})
%     set(h.tablemotornames, 'ColumnEditable',[false true false true false true false true false true])    
end

% Set virtual motor table data
% Update popup menu content
set(h.tablevirtualmotors, 'ColumnFormat',{char ['choose motor'; diffmotors]'})

guidata(hObj, h);

function creatediffractometer(hObj,~)
% Callback for import of motor names
h = guidata(hObj);

% get positioner data from table data
positionerdata = string(get(h.tablemotornames, 'data'));

SourcePos = strcmp(positionerdata,'Source Positioner');
DetPos = strcmp(positionerdata,'Detector Positioner');
SamplePos = strcmp(positionerdata,'Sample Positioner');

% Get all motors
if size(positionerdata,2) == 2
	motors = positionerdata(:, 1);
    % Get motors for each positioner
    sourcemotors = motors(SourcePos(:, 2));
    detmotors = motors(DetPos(:, 2));
    samplemotors = motors(SamplePos(:, 2));
elseif size(positionerdata,2) == 4
    motors = positionerdata(:, [1, 3]);
    % Get motors for each positioner
    sourcemotors = motors(SourcePos(:, [2,4]));
    detmotors = motors(DetPos(:, [2,4]));
    samplemotors = motors(SamplePos(:, [2,4]));
elseif size(positionerdata,2) == 6
    motors = positionerdata(:, [1, 3, 5]);
    % Get motors for each positioner
    sourcemotors = motors(SourcePos(:, [2,4,6]));
    detmotors = motors(DetPos(:, [2,4,6]));
    samplemotors = motors(SamplePos(:, [2,4,6]));
elseif size(positionerdata,2) == 8
    motors = positionerdata(:, [1, 3, 5, 7]);
    % Get motors for each positioner
    sourcemotors = motors(SourcePos(:, [2,4,6,8]));
    detmotors = motors(DetPos(:, [2,4,6,8]));
    samplemotors = motors(SamplePos(:, [2,4,6,8]));
end

% assignin('base','sourcemotors',sourcemotors)
% assignin('base','detmotors',detmotors)
% assignin('base','samplemotors',samplemotors)

% get motor names for virtual motors
virtualmotordata = get(h.tablevirtualmotors, 'data');

assignin('base','virtualmotordata',virtualmotordata)

% Get diffractometer name defined by user
Diffname = get(h.enterdifffilename,'String');

% Create diffractometer
Diffractometer = Measurement.Diffractometer;
Diffractometer.Detector = Measurement.Detector;
Diffractometer.Name = Diffname;

% Add source positioners
for k = 1:length(sourcemotors)
    Diffractometer.SourcePositioner.(sourcemotors(k)) = Measurement.Motor;
end

% Add sample positioners
for k = 1:length(samplemotors)
    Diffractometer.SamplePositioner.(samplemotors(k)) = Measurement.Motor;
end

% Add detector positioners
for k = 1:length(detmotors)
    Diffractometer.DetectorPositioner.(detmotors(k)) = Measurement.Motor;
end

% Define virtual motors
Diffractometer.VirtualMotors.omega = char(h.usermotornames(1,2));
Diffractometer.VirtualMotors.tth = char(h.usermotornames(2,2));
Diffractometer.VirtualMotors.phi = char(h.usermotornames(3,2));
Diffractometer.VirtualMotors.psi = char(h.usermotornames(4,2));

% Check for SPEC format
SPECFormatCheck = get(h.checkboxSelectFileFormat,'Value');
Diffractometer.CheckSPECformat = SPECFormatCheck;

% Define structure with literals for file import
if SPECFormatCheck == 1
    % Define literals
    Diffractometer.ImportLiterals.FileName = get(h.defineliteralSPECFilenames,'String');
    Diffractometer.ImportLiterals.ScanName = get(h.defineScanName,'String');
    Diffractometer.ImportLiterals.MotorNames = get(h.defineliteralSPECMotornames,'String');
    Diffractometer.ImportLiterals.MotorValues = get(h.defineliteralSPECMotorValues,'String');
    Diffractometer.ImportLiterals.NumberDetector = get(h.defineliteralSPECNumDet,'String');
    Diffractometer.ImportLiterals.Channels = get(h.defineliteralSPECChannels,'String');
    Diffractometer.ImportLiterals.Intensities = get(h.defineliteralSPECIntensities,'String');
    Diffractometer.ImportLiterals.Date = get(h.defineliteralSPECDate,'String');
    Diffractometer.ImportLiterals.Times = get(h.defineliteralSPECTimes,'String');
    Diffractometer.ImportLiterals.Temp = get(h.defineliteralSPECTemp,'String');
    Diffractometer.ImportLiterals.RingCurrent = get(h.defineliteralSPECRingCurrent,'String'); 
    Diffractometer.ImportLiterals.LastLineFH = get(h.defineLastLineHeader,'String');
    Diffractometer.ImportLiterals.LastLineSH = get(h.defineLastLineScanHeader,'String');
    % Define format for file name literal
    Diffractometer.ImportLiterals.FormatFileName = get(h.defineSampleNameFormat,'String'); % Überarbeiten
    % Define stress analysis parameters (HZB internal)
    Diffractometer.ImportLiterals.PhiStressInternal = '#phiP';
    Diffractometer.ImportLiterals.PsiStressInternal = '#psiP';
    Diffractometer.ImportLiterals.EtaStressInternal = '#eta';
else
    % Define literals for non SPEC files 
    Diffractometer.ImportLiterals.FileName = get(h.defineSampleNameLiteral,'String');
    Diffractometer.ImportLiterals.ScanName = get(h.defineScanName,'String');
    Diffractometer.ImportLiterals.ChannelStart = get(h.defineChannelStart,'String');
    Diffractometer.ImportLiterals.ChannelEnd = get(h.defineChannelEnd,'String');
    Diffractometer.ImportLiterals.LastLineFH = get(h.defineLastLineHeader,'String');
    Diffractometer.ImportLiterals.LastLineSH = get(h.defineLastLineScanHeader,'String');
    % Define format for file name literal
    Diffractometer.ImportLiterals.FormatFileName = get(h.defineSampleNameFormat,'String');
    % Define motor names and literals
    Diffractometer.ImportLiterals.MotorNames = h.MotorNamesUser;
    Diffractometer.ImportLiterals.Motorvalues = h.LiteralsUser;    
end

% Diffractometer.ImportLiterals.

Diffractometer.SaveToFile(Diffname)

guidata(hObj, h);

function clearbuttondown(hObj,~)
% ButtonDownFunc when user presses on the edit field
set(hObj, 'String','','Enable','on');
uicontrol(hObj);

function updatetableusermotordata(hObj, eventdata)
% Callback for updating user selected background points table 
h = guidata(hObj);
% get user sleceted motor names for virtual motors
h.usermotornames = eventdata.Source.Data;
guidata(hObj, h);