%% Change X-lim of stress plot
h.NoiseCorrectionbutton = uicontrol( ...
'Parent', h.Tabs(1), ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.6455 0.5175 0.05 0.03], ...
'String', 'Noise correction Mythen', ...
'Tag', 'NoiseCorrectionbutton', ...
'Callback', {@NoiseCorrection, h} ...
);


% Create new window that opens when button is pushed
if screenWidth < 5120
    h.NoiseCorrectionbutton = figure('menubar','none','units','normalized','Position',[0.45 0.5 0.15 0.08],'Name', 'Noise correction for Mythen detector','NumberTitle','off','Visible','off');
else
    h.NoiseCorrectionbutton = figure('menubar','none','units','normalized','Position',[0.25 0.5 0.08 0.07],'Name', 'Noise correction for Mythen detector','NumberTitle','off','Visible','off');
end

% Create graphic elements
h.XlimMaxname = uicontrol('Style', 'text',...
'Parent', h.Xlimfig,...
'Units','normalized',...
'Position', [0.05 0.705 0.3 0.25],...
'String', 'Min',...
'FontSize', 14,...
'HorizontalAlignment', 'right');    
h.XlimMaxname1 = uicontrol('Style', 'text',...
'Parent', h.Xlimfig,...
'Units','normalized',...
'Position', [0.375 0.775 0.075 0.175],...
'String', '=',...
'FontSize', 14,...
'HorizontalAlignment', 'left');    
h.editXlimMin  = uicontrol('Style','edit',...
'String', '0',...
'FontSize', 12,...
'Tag', 'editXlimMax',...
'Units','normalized',...
'Position',[0.45 0.7125 0.2 0.225],...
'Parent',h.Xlimfig);

h.XlimMinname = uicontrol('Style', 'text',...
'Parent', h.Xlimfig,...
'Units','normalized',...
'Position', [0.05 0.405 0.3 0.25],...
'String', 'Max',...
'FontSize', 14,...
'HorizontalAlignment', 'right');    
h.XlimMinname1 = uicontrol('Style', 'text',...
'Parent', h.Xlimfig,...
'Units','normalized',...
'Position', [0.375 0.475 0.075 0.175],...
'String', '=',...
'FontSize', 14,...
'HorizontalAlignment', 'left');    
h.editXlimMax  = uicontrol('Style','edit',...
'String', '0',...
'FontSize', 12,...
'Tag', 'editXlimMin',...
'Units','normalized',...
'Position',[0.45 0.4125 0.2 0.225],...
'Parent',h.Xlimfig);

h.XlimTickname = uicontrol('Style', 'text',...
'Parent', h.Xlimfig,...
'Units','normalized',...
'Position', [0.05 0.105 0.3 0.25],...
'String', 'Tick mark',...
'FontSize', 14,...
'HorizontalAlignment', 'right');    
h.XlimTickname1 = uicontrol('Style', 'text',...
'Parent', h.Xlimfig,...
'Units','normalized',...
'Position', [0.375 0.175 0.075 0.175],...
'String', '=',...
'FontSize', 14,...
'HorizontalAlignment', 'left');    
h.editXlimTick  = uicontrol('Style','edit',...
'String', '0',...
'FontSize', 12,...
'Tag', 'editXlimTick',...
'Units','normalized',...
'Position',[0.45 0.1125 0.2 0.225],...
'Parent',h.Xlimfig);     

h.AcceptXEditButton = uicontrol( ...
'Parent', h.Xlimfig, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.7 0.5 0.275 0.3], ...
'String', 'Accept', ...
'FontSize', 11,...
'Tag', 'AcceptXButton', ...
'Callback', {@acceptXlimEdit, h} ...
);   
h.CancelXEditButton = uicontrol( ...
'Parent', h.Xlimfig, ...
'Style', 'Pushbutton', ...
'Units', 'Normalized', ...
'Position', [0.7 0.1 0.275 0.3], ...
'String', 'Cancel', ...
'FontSize', 11,...
'Tag', 'CancelXButton', ...
'Callback', {@cancelXlimEdit, h} ...
); 