classdef EnergyPosCalib < rietveld.func.spec.EnergyPosInterface
%% (* EnergyPos *)
% Berechnung der theoretischen Energielagen.
% -------------------------------------------------------------------------
	
	methods (Access = public)
		
		function ep = execute(obj, ~, general, meas, phase, spec)
			
			% Passende Struktur wird ausgewaehlt
			if (general.LatticeParam1 ~= 0 && general.LatticeParam2 == 0 && general.LatticeParam3 == 0)
				LatticeParam_a = general.LatticeParam1;
				LatticeParam_b = general.LatticeParam1;
				LatticeParam_c = general.LatticeParam1;
			elseif (general.LatticeParam1 ~= 0 && general.LatticeParam2 == 0 && general.LatticeParam3 ~= 0)
				LatticeParam_a = general.LatticeParam1;
				LatticeParam_b = general.LatticeParam1;
				LatticeParam_c = general.LatticeParam3;
			elseif (general.LatticeParam1 ~= 0 && general.LatticeParam2 ~= 0 && general.LatticeParam3 ~= 0)
				LatticeParam_a = general.LatticeParam1;
				LatticeParam_b = general.LatticeParam2;
				LatticeParam_c = general.LatticeParam3;
			end
			
			% Berechnung der Gitterabstaende
			CellVolume = LatticeParam_a .* LatticeParam_b .* LatticeParam_c .* ...
				sqrt(1 - cosd(phase.Alpha).^2 - cosd(phase.Beta).^2 - cosd(phase.Gamma).^2 + ...
				2 .* cosd(phase.Alpha) .* cosd(phase.Beta) .* cosd(phase.Gamma));
			S_11 = LatticeParam_b.^2 .* LatticeParam_c.^2 .* sind(phase.Alpha).^2;
			S_22 = LatticeParam_a.^2 .* LatticeParam_c.^2 .* sind(phase.Beta).^2;
			S_33 = LatticeParam_a.^2 .* LatticeParam_b.^2 .* sind(phase.Gamma).^2;
			S_12 = LatticeParam_a .* LatticeParam_b .* LatticeParam_c.^2 .* ...
				(cosd(phase.Alpha) .* cosd(phase.Beta) - cosd(phase.Gamma));
			S_23 = LatticeParam_a.^2 .* LatticeParam_b .* LatticeParam_c .* ...
				(cosd(phase.Beta) .* cosd(phase.Gamma) - cosd(phase.Alpha));
			S_13 = LatticeParam_a .* LatticeParam_b.^2 .* LatticeParam_c .* ...
				(cosd(phase.Gamma) .* cosd(phase.Alpha) - cosd(phase.Beta));
			
			% Umrechnung auf Energieskala
			ep = 6.199 ./ (sind(meas.TwoTheta./2) * CellVolume) .* ...
				sqrt(S_11.* (general.H).^2 + S_22 .* (general.K).^2 + S_33 .* (general.L).^2 + ...
				2 .* S_12 .* general.H .* general.K + 2 .* S_23 .* general.K .* general.L + ...
				2 .* S_13 .* general.H .* general.L);
% 			ep
			% Korrektur
% 			deltaE = obj.sfwc.EnergyCalib.execute(ep, general, meas, phase, spec);

			ep = ep + polyval([spec.DeltaEnergy_c, spec.DeltaEnergy_b, spec.DeltaEnergy_a], ep);
% 			disp(polyval([spec.DeltaEnergy_c, spec.DeltaEnergy_b, spec.DeltaEnergy_a], ep))
% 			disp(ep)
		end

		function obj = addFunctionParameters(obj, pc)

			obj.addParameter(pc, 'TwoTheta',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', false);
			obj.addParameter(pc, 'LatticeParam1',...
				'Category', 'Energy Positions',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'LatticeParam2',...
				'Category', 'Energy Positions',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'LatticeParam3',...
				'Category', 'Energy Positions',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'Alpha',...
				'Category', 'Energy Positions',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Beta',...
				'Category', 'Energy Positions',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Gamma',...
				'Category', 'Energy Positions',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'H',...
				'Category', 'Energy Positions',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'K',...
				'Category', 'Energy Positions',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'L',...
				'Category', 'Energy Positions',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', true);
			
			obj.addParameter(pc, 'DeltaEnergy_a',...
				'Category', 'Energy Positions',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'DeltaEnergy_b',...
				'Category', 'Energy Positions',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'DeltaEnergy_c',...
				'Category', 'Energy Positions',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
		end
	end
	
	methods (Access = protected)
		
		function obj = initSubFunctions(obj)
			
% 			obj.addSubFunction('EnergyCalib', 'rietveld.func.spec.corr.EnergyCalibInterface', rietveld.func.spec.corr.EnergyCalibInterface());
		end
	end
end

