classdef DummyPeaks < rietveld.func.spec.dummy.DummyInterface

	methods (Access = public)
		
		function Y = execute(obj, X, ~, ~, ~, spec)
			
			Y = 0;
			
			for i = 1:length(spec.DummyPosition)
% 				Y = Y + spec.DummyMixingFactor(i) .* ...
% 					(spec.DummyIntensity(i) .* exp(-(((X - spec.DummyPosition(i)) ./ spec.DummyWidth(i)).^2)./2)) + ...
% 					(1 - spec.DummyMixingFactor(i)) .* ...
% 					(spec.DummyIntensity(i) ./ (1 + 4 * ((X - spec.DummyPosition(i)) ./ spec.DummyWidth(i)).^2));
				
				Y = Y + spec.DummyMixingFactor(i) .* ...
					(spec.DummyIntensity(i) .* exp(- 4 * log(2) * (((X - spec.DummyPosition(i)) ./ spec.DummyWidth(i)).^2))) + ...
					(1 - spec.DummyMixingFactor(i)) .* ...
					(spec.DummyIntensity(i) ./ (1 + 4 * ((X - spec.DummyPosition(i)) ./ spec.DummyWidth(i)).^2));				
			end
		end
		
		function obj = addFunctionParameters(obj, pc)
			
			obj.addParameter(pc, 'DummyIntensity',...
				'Category', 'Dummy peaks',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true,...
				'Value', []);
			obj.addParameter(pc, 'DummyPosition',...
				'Category', 'Dummy peaks',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true,...
				'Value', []);
			obj.addParameter(pc, 'DummyWidth',...
				'Category', 'Dummy peaks',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true,...
				'Value', []);
			obj.addParameter(pc, 'DummyMixingFactor',...
				'Category', 'Dummy peaks',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true,...
				'Value', []);
			
% 			obj.addParameter(pc, 'Dummy_P_Size',...
% 				'Category', 'Dummy peaks',...
% 				'ParamSize', [NaN, 1],...
% 				'Constant', false,...
% 				'PhaseDep', false,...
% 				'SpecDep', true,...
% 				'Value', []);
% 			obj.addParameter(pc, 'Dummy_X_Size',...
% 				'Category', 'Dummy peaks',...
% 				'ParamSize', [NaN, 1],...
% 				'Constant', false,...
% 				'PhaseDep', false,...
% 				'SpecDep', true,...
% 				'Value', []);
% 			obj.addParameter(pc, 'Dummy_U_Strain',...
% 				'Category', 'Dummy peaks',...
% 				'ParamSize', [NaN, 1],...
% 				'Constant', false,...
% 				'PhaseDep', false,...
% 				'SpecDep', true,...
% 				'Value', []);
% 			obj.addParameter(pc, 'Dummy_Y_Strain',...
% 				'Category', 'Dummy peaks',...
% 				'ParamSize', [NaN, 1],...
% 				'Constant', false,...
% 				'PhaseDep', false,...
% 				'SpecDep', true,...
% 				'Value', []);
		end
	end
	
	methods (Access = protected)
		
		function obj = initSubFunctions(obj)
		end
	end
end

