classdef Asymdoublesig < rietveld.func.spec.bkg.BkgInterface
	
	methods (Access = public)
		
		function Y = execute(obj, X, ~, ~, ~, spec)
		
			Y = 0;
			for i = 1:size(spec.MaxAmp, 1)	
				Ytmp = (spec.MaxAmp(i)./(1 + exp(-(X - spec.Center(i) + (spec.Width(i)./2))./spec.Shape1(i)))).*...
				(1 - (1./(1 + exp(-(X - spec.Center(i) - (spec.Width(i)./2))./(spec.Shape2(i))))));
				Y = Y + Ytmp;
			end
		end
		
		function obj = addFunctionParameters(obj, pc)
			
			obj.addParameter(pc, 'MaxAmp',...
				'Category', 'Background',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'Center',...
				'Category', 'Background',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'Width',...
				'Category', 'Background',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'Shape1',...
				'Category', 'Background',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'Shape2',...
				'Category', 'Background',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
		end
	end
end
