classdef Splitpoly2 < rietveld.func.spec.bkg.BkgInterface
	
	methods (Access = public)
		
		function Y = execute(obj, X, ~, meas, ~, spec)
			
            Y1 = polyval(spec.Background1, X(meas.BkgRange(1):meas.BkgRange(2)));
            
            Y2 = polyval(spec.Background2, X(meas.BkgRange(3):meas.BkgRange(4)));
            
            Y1 = Y1';
            Y2 = Y2';

            Y = [Y1,Y2]';

            
		end
		
		function obj = addFunctionParameters(obj, pc)
			
			obj.addParameter(pc, 'Background1',...
				'Category', 'Background',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
            obj.addParameter(pc, 'Background2',...
				'Category', 'Background',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
            obj.addParameter(pc, 'BkgRange',...
				'Category', 'Background',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', false);
		end
	end
end

