function filterbutton_Callback(source,~,data1,data2)
    % This callback manages the filter options for the search and match
    % results.
    Plothandles = guidata(gcbo);
    % Load table data from search and match.
    tableSaM = Plothandles.tableSaM;
    % Numver of matches from matchedit.
    matches = data2.String;
    % Creat new figure where the filter options can be applied.
    f = figure('ToolBar', 'None',...
        'MenuBar', 'None',...
        'Units', 'normalized',...
        'Position', [0.2475 0.2 0.505 0.6],...
        'Name', 'Filter options for Search and Match results',...
        'NumberTitle','off');
    % Create table with results from search and match.
    table = uitable('Units', 'normalized',...   
        'FontSize', 8,...
        'Position', [0.05 0.25 0.9 0.73],...
        'Parent',f,...
        'Tag', 'tablefilter',...
        'ColumnName', {'Plot','PDFCardNumber','ElementSymbol','ElementName','spaceGroupSymbol','spaceGroupNumber'},...
        'ColumnWidth', {30 100 150 240 140 140},...
        'ColumnFormat', ['logical', {[]}],...
        'Data', tableSaM.Data);
    % Set Figure visible.
    set(f, 'Visible', 'on');
    
    %% Number of matches
    % Show how many matches were found.
    textmatchfilter = uicontrol('Style', 'text',...
        'Parent', f,...
        'Units','normalized',...
        'Position', [0.5125 0.106 0.1 0.1],...
        'String', 'Matches found',...
        'FontSize', 10,...
        'HorizontalAlignment', 'left');
    matcheditfilter  = uicontrol('Style','edit',...
        'String', num2str(matches),...
        'Units','normalized',...
        'Tag', 'matchedit',...
        'Position',[0.4 0.17 0.1 0.05],...
        'Parent',f);
    %% Filter for element symbol(s)
    % This filter allows to search the results from search and match for a
    % specific element (single element), a number of elements or elements
    % of a compound.
    FilterElementtxt = uicontrol('Style', 'text',...
        'Parent', f,...
        'Units', 'normalized',...
        'Position', [0.05 0.21 0.15 0.03],...
        'String' , 'Element filter',...
        'FontWeight', 'bold',...
        'FontSize', 10,...
        'HorizontalAlignment', 'left');
    FilterElementedit = uicontrol('Style', 'edit',...
        'Parent', f,...
        'Units', 'normalized',...
        'Tag', 'filterelementedit',...
        'Position', [0.05 0.18 0.15 0.03],...
        'String' , 'Enter element(s) symbol(s)');
    Filtercheckbox = uicontrol('Style', 'checkbox',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'filtercheckbox',...
        'Position', [0.225 0.1675 0.14 0.03],... 
        'String', 'Search for compound');
    Filtercheckbox1 = uicontrol('Style', 'checkbox',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'filtercheckbox1',...
        'Position', [0.225 0.1925 0.14 0.03],... 
        'String', 'Single Element');
    FilterElementsearchbut = uicontrol('Style', 'PushButton',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'searchbutton',...
        'Position', [0.05 0.1425 0.07 0.03],... 
        'String', 'Run', ... 
        'Callback', {@FilterElementsearchbut_Callback, table, FilterElementedit, Filtercheckbox, Filtercheckbox1, matcheditfilter});
    ResetDatabut = uicontrol('Style', 'PushButton',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'resetbutelement',...
        'Position', [0.1225 0.1425 0.07 0.03],... 
        'String', 'Reset', ... 
        'Callback', {@ResetData_Callback, table, tableSaM, matcheditfilter});
    
    %% Filter for element name(s)
    FilterNametxt = uicontrol('Style', 'text',...
        'Parent', f,...
        'Units', 'normalized',...
        'Position', [0.05 0.095 0.2 0.03],...
        'String' , 'Element Name filter',...
        'FontWeight', 'bold',...
        'FontSize', 10,...
        'HorizontalAlignment', 'left');
    FilterNameedit = uicontrol('Style', 'edit',...
        'Parent', f,...
        'Units', 'normalized',...
        'Tag', 'filterelementedit',...
        'Position', [0.05 0.065 0.15 0.03],...
        'String' , 'Enter element(s) name(s)');
    FilterNamesearchbut = uicontrol('Style', 'PushButton',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'searchbutton',...
        'Position', [0.05 0.027 0.07 0.03],... 
        'String', 'Run', ... 
        'Callback', {@FilterNamesearchbut_Callback, table, FilterNameedit, matcheditfilter});
    ResetDatabut = uicontrol('Style', 'PushButton',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'resetbutname',...
        'Position', [0.1225 0.027 0.07 0.03],... 
        'String', 'Reset', ... 
        'Callback', {@ResetData_Callback, table, tableSaM, matcheditfilter});
    
    %% Filter for crystal system
    FilterCrystalSystemtxt = uicontrol('Style', 'text',...
        'Parent', f,...
        'Units', 'normalized',...
        'Position', [0.225 0.095 0.2 0.03],...
        'String' , 'Crystal system filter',...
        'FontWeight', 'bold',...
        'FontSize', 10,...
        'HorizontalAlignment', 'left');
    FilterCrystalSystemopoup = uicontrol('Style', 'popup',...
        'Parent',f,...
        'Units', 'normalized',...
        'String', {'cubic','hexagonal','trigonal','tetragonal','orthorhombic','monoclininc','triclinc'},...
        'Position', [0.225 0.0445 0.1 0.05],...
        'background','white',...
        'Value',1,...
        'Callback',@FilterCrystalSystemopoup_Callback);
    FilterCrystalSystemsearchbut = uicontrol('Style', 'PushButton',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'searchbutton',...
        'Position', [0.225 0.027 0.07 0.03],... 
        'String', 'Run', ... 
        'Callback', {@FilterCrystalSystemsearchbut_Callback, table, FilterCrystalSystemopoup, matcheditfilter});
    % Rest button
    ResetDatabut = uicontrol('Style', 'PushButton',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'resetbutcrystalsystem',...
        'Position', [0.2975 0.027 0.07 0.03],... 
        'String', 'Reset', ... 
        'Callback', {@ResetData_Callback, table, tableSaM, matcheditfilter});
    
    %% Creat Ok and Cancel Button
    % Ok button. The filtered table data is transfered to the results tab.
    okbut = uicontrol('Style', 'PushButton',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'okbutton',...
        'Position', [0.8055 0.025 0.07 0.06],... 
        'String', 'Ok', ... 
        'Callback', {@OnOkClick_Callback, f, table, tableSaM});
    % Cancel button. The filter are dismissed and the initial results from
    % search and match are transfered to the results tab.
    cancelbut = uicontrol('Style', 'PushButton',...
        'Parent',f,...
        'Units', 'normalized',...
        'Tag', 'cancelbutton',...
        'Position', [0.88 0.025 0.07 0.06],... 
        'String', 'Cancel', ... 
        'Callback', {@OnCancelClick_Callback, f, table, tableSaM});
    
    Plothandles.tableFilter = table;
    Plothandles.filterElementedit = FilterElementedit;
    Plothandles.filtercheckbox = Filtercheckbox;
    Plothandles.filtercheckbox1 = Filtercheckbox1;
    Plothandles.filterCrystalSystemopoup = FilterCrystalSystemopoup;
    guidata(gcbo,Plothandles);
end

