classdef Modgeneralsigma < rietveld.func.spec.diffpeaks.strain.StrainInterface

	methods (Access = public)
		
		function eps_hkl = execute(obj, acm, general, meas, phase, spec)
		% acm wird aus Effizienzgruenden direkt uebergeben
			
			tau = obj.sfwc.Tau.execute(acm, general, meas, phase, spec);
% 			disp(tau)
			sigma_11 = phase.Sigma11StressCoef1./(phase.Sigma11StressCoef3.*tau + 1) + ...
				phase.Sigma11StressCoef2.*tau./(phase.Sigma11StressCoef3.*tau + 1).^2;
            
            sigma_22 = phase.Sigma22StressCoef1./(phase.Sigma22StressCoef3.*tau + 1) + ...
				phase.Sigma22StressCoef2.*tau./(phase.Sigma22StressCoef3.*tau + 1).^2;
			
            % StressCoefa = Spannungswert von sigma33
			% StressCoefb = Wert für die Tiefe bei der sigma33 beginnt
			sigma_33 = phase.Sigma33StressCoefa .* exp(-phase.Sigma33StressCoefb./tau);
            
            sigma_12 = phase.Sigma12StressCoef1./(phase.Sigma12StressCoef3.*tau + 1) + ...
				phase.Sigma12StressCoef2.*tau./(phase.Sigma12StressCoef3.*tau + 1).^2;
            
            sigma_13 = phase.Sigma13StressCoef1./(phase.Sigma13StressCoef3.*tau + 1) + ...
				phase.Sigma13StressCoef2.*tau./(phase.Sigma13StressCoef3.*tau + 1).^2;
            
            sigma_23 = phase.Sigma23StressCoef1./(phase.Sigma23StressCoef3.*tau + 1) + ...
				phase.Sigma23StressCoef2.*tau./(phase.Sigma23StressCoef3.*tau + 1).^2; 
			
			eps_hkl = general.DEK_S2 .* (sind(spec.Psi)^2 .* (sigma_11.*cosd(spec.Phi).^2 + ...
                      sigma_22 .* sind(spec.Phi).^2 + sigma_12 .* sind(2.*spec.Phi) - sigma_33) + sigma_33 + ...
                      sind(2.*spec.Psi) .* (sigma_13.*cosd(spec.Phi) + sigma_23.*sind(spec.Phi))) + ...
					  general.DEK_S1 .* (sigma_11 + sigma_22 + sigma_33);
% 			disp(sigma_33)	  

		end

		function obj = addFunctionParameters(obj, pc)

			obj.addParameter(pc, 'DEK_S1',...
				'Category', 'Material',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'DEK_S2',...
				'Category', 'Material',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'TwoTheta',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', false);
			obj.addParameter(pc, 'Psi',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', true);
            obj.addParameter(pc, 'Phi',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', true);
% 			obj.addParameter(pc, 'StressCoef',...
% 				'Category', 'Peaks',...
% 				'ParamSize', [4, 1],...
% 				'Constant', false,...
% 				'PhaseDep', true,...
% 				'SpecDep', false);
			obj.addParameter(pc, 'Sigma11StressCoef1',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma11StressCoef2',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma11StressCoef3',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
            obj.addParameter(pc, 'Sigma22StressCoef1',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma22StressCoef2',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma22StressCoef3',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
            obj.addParameter(pc, 'Sigma12StressCoef1',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma12StressCoef2',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma12StressCoef3',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
            obj.addParameter(pc, 'Sigma13StressCoef1',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma13StressCoef2',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma13StressCoef3',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
            obj.addParameter(pc, 'Sigma23StressCoef1',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma23StressCoef2',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma23StressCoef3',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma33StressCoefa',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'Sigma33StressCoefb',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
		end
	end
	
	methods (Access = protected)
		
		function obj = initSubFunctions(obj)
			
			obj.addSubFunction('Tau', 'rietveld.func.spec.diffpeaks.Tau', rietveld.func.spec.diffpeaks.Tau());
		end
	end
	
end



