<<<<<<< .mine
%% Choice of scattering angle TwoTheta
config.configParameter('TwoTheta',...
	'Value', 16);
psiTmp = [0; 4; 8; 12; 16; 20; 24; 28; 32; 36; 40; 44; 48; 52; 56; 60;...
	64; 68; 72; 74; 76; 78; 80; 81; 82; 83; 84; 85; 86; 87; 88; 89];
for i = 1:numberOfSpecs
	config.configParameter('Psi',...
		'Value', psiTmp(i),...
		'SpecIndex', i);
end

%% Input of photon energies of principal K-, L-shell emmision lines
config.configParameter('FluorPos_K',...
	'Value', zeros(0,1));
config.configParameter('FluorPos_L',...
	'Value', 21.4);
config.configParameter('FluorInt_K',...
	'Value', zeros(0,1));
config.configParameter('FluorInt_L',...
	'Value', 1.00);

%% Input of the h k l values and multiplicity m values
hklTmp = [1 1 0 12;...
    2 0 0 6;...
    2 1 1 24;...
    2 2 0 12;...
    3 1 0 24;...
    2 2 2 8;...
    3 2 1 48];
config.configParameter('H',...
	'Value', hklTmp(:,1),...
	'SpecIndex', 1:10);
config.configParameter('H',...
	'Value', hklTmp(([1:5,7]),1),...
	'SpecIndex', 11:23);
config.configParameter('H',...
	'Value', hklTmp((1:3),1),...
	'SpecIndex', 24:26);
config.configParameter('H',...
	'Value', hklTmp(([1,3]),1),...
	'SpecIndex', 27:29);
config.configParameter('K',...
	'Value', hklTmp(:,2),...
	'SpecIndex', 1:10);
config.configParameter('K',...
	'Value', hklTmp(([1:5,7]),2),...
	'SpecIndex', 11:23);
config.configParameter('K',...
	'Value', hklTmp((1:3),2),...
	'SpecIndex', 24:26);
config.configParameter('K',...
	'Value', hklTmp(([1,3]),2),...
	'SpecIndex', 27:29);
config.configParameter('L',...
	'Value', hklTmp(:,3),...
	'SpecIndex', 1:10);
config.configParameter('L',...
	'Value', hklTmp(([1:5,7]),3),...
	'SpecIndex', 11:23);
config.configParameter('L',...
	'Value', hklTmp((1:3),3),...
	'SpecIndex', 24:26);
config.configParameter('L',...
	'Value', hklTmp(([1,3]),3),...
	'SpecIndex', 27:29);
config.configParameter('Multiplicity',...
	'Value', hklTmp(:,4),...
	'SpecIndex', 1:10);
config.configParameter('Multiplicity',...
	'Value', hklTmp(([1:5,7]),4),...
	'SpecIndex', 11:23);
config.configParameter('Multiplicity',...
	'Value', hklTmp((1:3),4),...
	'SpecIndex', 24:26);
config.configParameter('Multiplicity',...
	'Value', hklTmp(([1,3]),4),...
	'SpecIndex', 27:29);
config.configParameter('Alpha',...
	'Value', 90);
config.configParameter('Beta',...
	'Value', 90);
config.configParameter('Gamma',...
	'Value', 90);
ringCurrentTmp = [268.414; 268.151; 267.897; 267.637; 267.377; 267.117;...
    266.862; 266.612; 266.354; 266.1; 265.844; 265.596; 265.344;...
    265.09; 264.835; 264.59; 264.338; 264.087; 263.836; 263.593;...
    263.352; 263.113; 262.874; 262.637; 262.405; 262.171; 261.932;...
    261.7; 261.471];
for i = 1:numberOfSpecs
	config.configParameter('RingCurrent',...
		'Value', ringCurrentTmp(i),...
		'SpecIndex', i);
end
deadTimeTmp = [14.5; 16.4333; 16.5; 15.8333; 14.7666; 13.4; 11.8; 10.4;...
    9.166666667; 8.266666667; 7.2; 6.2; 5.6; 4.9; 4.266666667;...
    3.833333333; 3.4; 2.9; 2.5; 2.4; 2.266666667; 2.4; 2.633333333;...
    2.7; 2.766666667; 2.966666667; 3.066666667; 3.266666667; 3.4];
for i = 1:numberOfSpecs
	config.configParameter('DeadTime',...
		'Value', deadTimeTmp(i),...
		'SpecIndex', i);
end

%% Input of the DEK values
DEK_S_Tmp = [-1.27e-006 5.80e-006;  %110
            -1.90e-006 7.70e-006; %200
            -1.27e-006 5.80e-006; %211
            -1.27e-006 5.80e-006; %220
            -1.67e-006 7.02e-006; %310
            -1.05e-006 5.17e-006; %222
            -1.27e-006 5.80e-006;]; %321
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp(:,1),...
	'SpecIndex', 1:10);
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp(([1:5,7]),1),...
	'SpecIndex', 11:23);
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp((1:3),1),...
	'SpecIndex', 24:26);
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp(([1,3]),1),...
	'SpecIndex', 27:29);
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp(:,2),...
	'SpecIndex', 1:10);
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp(([1:5,7]),2),...
	'SpecIndex', 11:23);
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp((1:3),2),...
	'SpecIndex', 24:26);
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp(([1,3]),2),...
	'SpecIndex', 27:29);

%% Input of the attenuation factors
config.configParameter('DensityAir',...
	'Value', 1.293e-003);
load('d:\Profile\hrp\Eigene Dateien\MATLAB\Rietveld\TestDaten\Air_Absorption.mat');
config.configParameter('X_airabsorption',...
	'Value', X_airabsorption);
config.configParameter('Y_airabsorption',...
	'Value', Y_airabsorption_en);
config.configParameter('DetectorDistance',...
	'Value', 110);

%% material absorption correction
config.configParameter('Density',...
	'Value', 7.870);
load('d:\Profile\hrp\Eigene Dateien\MATLAB\Rietveld\TestDaten\Fe_absorption_XCOM.mat');
config.configParameter('X_abs',...
	'Value', X_abs);
config.configParameter('Y_abs',...
	'Value', Y_abs);

%% structure factor calculation
% load('C:\Users\hrp\Documents\MATLAB\Rietveld\TestDaten\AtomSF.mat')
% config.configParameter('SF_a',...
% 	'Value', Atomdata(52,[1 3 5 7]));
% config.configParameter('SF_b',...
% 	'Value', Atomdata(52,[2 4 6 8]));
% config.configParameter('SF_c',...
% 	'Value', Atomdata(52,9));
% config.configParameter('APConst',...
% 	'Value', [0 0 0;...
% 				1/2 1/2 1/2]);
% config.configParameter('APFitPattern',...
% 	'Value', [0 0 0;...
% 				0 0 0]);
% config.configParameter('APFitParams',...
% 	'Value', 0);
% config.configParameter('AtomCoordCnts',...
% 	'Value', 0);

%% FitParameter for the FWHM and the line position calibration
config.configParameter('FluorScaleFactor_K',...
	'Value', 1,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorScaleFactor_L',...
	'Value', 1,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', true);
config.configParameter('FluorDeltaEnergy_K',...
	'Value', zeros(3,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorDeltaEnergy_L',...
	'Value', zeros(3,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorU_K',...
	'Value', 0.0025,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorW_K',...
	'Value', 0.0005,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorU_L',...
	'Value', 0.0025,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorW_L',...
	'Value', 0.0005,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);

%% Escape peaks
% config.configParameter('EscapeInt_Alpha',...
% 	'Value', ones(3,1));
% config.configParameter('EscapeInt_Beta',...
% 	'Value', ones(3,1));
% config.configParameter('EscapeAlphaInd',...
% 	'Value', [2; 3; 4]);
% config.configParameter('EscapeBetaInd',...
% 	'Value', [2; 3; 4]);
% config.configParameter('EscapeScaleFactor_Alpha',...
% 	'Value', 1,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeScaleFactor_Beta',...
% 	'Value', 1,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeU_Alpha',...
% 	'Value', 0.0025,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeU_Beta',...
% 	'Value', 0.0005,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeW_Alpha',...
% 	'Value', 0.0025,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeW_Beta',...
% 	'Value', 0.0005,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);

%% Phase
config.configParameter('ScaleFactor',...
	'Value', 1,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', true);
config.configParameter('StructureFactor',...
	'Value', ones(7,1).*100,...
	'SpecIndex', 1:10,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StructureFactor',...
	'Value', ones(6,1).*100,...
	'SpecIndex', 11:23,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StructureFactor',...
	'Value', ones(3,1).*100,...
	'SpecIndex', 24:26,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StructureFactor',...
	'Value', ones(2,1).*100,...
	'SpecIndex', 27:29,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DeltaEnergy_a',...
	'Value', -0.0268,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DeltaEnergy_b',...
	'Value',  0.0028,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DeltaEnergy_c',...
	'Value', -3.4234e-005,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('LatticeParam1',...
	'Value', 2.865,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('LatticeParam2',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('LatticeParam3',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StressCoef',...
	'Value', [0; 0; 0; 0],...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('P_Size',...
	'Value', 0.0392,...
	'LowerConstraint', 0.0392,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('U_Strain',...
	'Value', 3.1171e-005,...
	'LowerConstraint', 3.1171e-005,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('V_Detector',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('X_Size',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('Y_Strain',...
	'Value', 8.7785e-004,...
	'LowerConstraint', 8.7785e-004,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('Z_Detector',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('Background',...
	'Value', zeros(6,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', true);

out = fitter.executeFit(rc);=======
%% Choice of scattering angle TwoTheta
config.configParameter('TwoTheta',...
	'Value', 16);
psiTmp = [0; 4; 8; 12; 16; 20; 24; 28; 32; 36; 40; 44; 48; 52; 56; 60;...
	64; 68; 72; 74; 76; 78; 80; 81; 82; 83; 84; 85; 86; 87; 88; 89];
for i = 1:numberOfSpecs
	config.configParameter('Psi',...
		'Value', psiTmp(i),...
		'SpecIndex', i);
end

%% Input of photon energies of principal K-, L-shell emmision lines
config.configParameter('FluorPos_K',...
	'Value', ones(1,1));
config.configParameter('FluorPos_L',...
	'Value', 21.4);
config.configParameter('FluorInt_K',...
	'Value', ones(1,1));
config.configParameter('FluorInt_L',...
	'Value', 1.00);

%% Input of the h k l values and multiplicity m values
hklTmp = [1 1 0 12;...
    2 0 0 6;...
    2 1 1 24;...
    2 2 0 12;...
    3 1 0 24;...
    2 2 2 8;...
    3 2 1 48];
config.configParameter('H',...
	'Value', hklTmp(:,1),...
	'SpecIndex', 1:22);
config.configParameter('H',...
	'Value', hklTmp(([1:5,7]),1),...
	'SpecIndex', 23:25);
config.configParameter('H',...
	'Value', hklTmp((1:5),1),...
	'SpecIndex', 26);
config.configParameter('H',...
	'Value', hklTmp(([1,3,4,5,7]),1),...
	'SpecIndex', 27);
config.configParameter('H',...
	'Value', hklTmp(([1,3,4,5]),1),...
	'SpecIndex', 28:29);
config.configParameter('K',...
	'Value', hklTmp(:,2),...
	'SpecIndex', 1:22);
config.configParameter('K',...
	'Value', hklTmp(([1:5,7]),2),...
	'SpecIndex', 23:25);
config.configParameter('K',...
	'Value', hklTmp((1:5),2),...
	'SpecIndex', 26);
config.configParameter('K',...
	'Value', hklTmp(([1,3,4,5,7]),2),...
	'SpecIndex', 27);
config.configParameter('K',...
	'Value', hklTmp(([1,3,4,5]),2),...
	'SpecIndex', 28:29);
config.configParameter('L',...
	'Value', hklTmp(:,3),...
	'SpecIndex', 1:22);
config.configParameter('L',...
	'Value', hklTmp(([1:5,7]),3),...
	'SpecIndex', 23:25);
config.configParameter('L',...
	'Value', hklTmp((1:5),3),...
	'SpecIndex', 26);
config.configParameter('L',...
	'Value', hklTmp(([1,3,4,5,7]),3),...
	'SpecIndex', 27);
config.configParameter('L',...
	'Value', hklTmp(([1,3,4,5]),3),...
	'SpecIndex', 28:29);
config.configParameter('Multiplicity',...
	'Value', hklTmp(:,4),...
	'SpecIndex', 1:22);
config.configParameter('Multiplicity',...
	'Value', hklTmp(([1:5,7]),4),...
	'SpecIndex', 23:25);
config.configParameter('Multiplicity',...
	'Value', hklTmp((1:5),4),...
	'SpecIndex', 26);
config.configParameter('Multiplicity',...
	'Value', hklTmp(([1,3,4,5,7]),4),...
	'SpecIndex', 27);
config.configParameter('Multiplicity',...
	'Value', hklTmp(([1,3,4,5]),4),...
	'SpecIndex', 28:29);
config.configParameter('Alpha',...
	'Value', 90);
config.configParameter('Beta',...
	'Value', 90);
config.configParameter('Gamma',...
	'Value', 90);
ringCurrentTmp = [142.412; 140.389; 138.415; 136.49 ; 134.616; 137.034; 262.941; 256.812;...
	251.067; 245.597; 240.376; 235.384; 230.602; 226.007; 221.582; 217.33; 213.335;...
	209.378; 205.526; 201.809; 198.32; 195.029; 191.789; 188.655; 185.588; 182.646;...
	179.785; 177.005; 174.307; 171.692; 169.124; 166.616];
for i = 1:numberOfSpecs
	config.configParameter('RingCurrent',...
		'Value', ringCurrentTmp(i),...
		'SpecIndex', i);
end
deadTimeTmp = [8.816666667; 8.895; 8.721666667; 8.418333333; 7.841666667; 5.781666667;...
	14.08; 12.785; 11.37; 9.966666667; 8.69; 7.411666667; 6.266666667; 5.328333333;...
	4.438333333; 3.73; 3.085; 2.583333333; 2.141666667; 2.015; 2.053333333; 2.896666667;...
	4.465; 5.366666667; 6.33; 1.303333333; 8.133333333; 9.265; 10.66666667; 12.06166667;...
	13.27666667; 14.33166667];
for i = 1:numberOfSpecs
	config.configParameter('DeadTime',...
		'Value', deadTimeTmp(i),...
		'SpecIndex', i);
end

%% Input of the DEK values
DEK_S_Tmp = [-1.27e-006 5.80e-006;  %110
            -1.90e-006 7.70e-006; %200
            -1.27e-006 5.80e-006; %211
            -1.27e-006 5.80e-006; %220
            -1.67e-006 7.02e-006; %310
            -1.05e-006 5.17e-006; %222
            -1.27e-006 5.80e-006;]; %321
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp(:,1),...
	'SpecIndex', 1:22);
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp(([1:5,7]),1),...
	'SpecIndex', 23:25);
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp((1:5),1),...
	'SpecIndex', 26);
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp(([1,3,4,5,7]),1),...
	'SpecIndex', 27);
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp(([1,3,4,5]),1),...
	'SpecIndex', 28:29);
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp(:,2),...
	'SpecIndex', 1:22);
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp(([1:5,7]),2),...
	'SpecIndex', 23:25);
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp((1:5),2),...
	'SpecIndex', 26);
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp(([1,3,4,5,7]),2),...
	'SpecIndex', 27);
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp(([1,3,4,5]),2),...
	'SpecIndex', 28:29);

%% Input of the attenuation factors
config.configParameter('DensityAir',...
	'Value', 1.293e-003);
load('C:\Users\hrp\Documents\MATLAB\Rietveld\TestDaten\Air_Absorption.mat');
config.configParameter('X_airabsorption',...
	'Value', X_airabsorption);
config.configParameter('Y_airabsorption',...
	'Value', Y_airabsorption_en);
config.configParameter('DetectorDistance',...
	'Value', 110);

%% material absorption correction
config.configParameter('Density',...
	'Value', 7.870);
load('C:\Users\hrp\Documents\MATLAB\Rietveld\TestDaten\Fe_absorption_XCOM.mat');
config.configParameter('X_abs',...
	'Value', X_abs);
config.configParameter('Y_abs',...
	'Value', Y_abs);

%% structure factor calculation
% load('C:\Users\hrp\Documents\MATLAB\Rietveld\TestDaten\AtomSF.mat')
% config.configParameter('SF_a',...
% 	'Value', Atomdata(52,[1 3 5 7]));
% config.configParameter('SF_b',...
% 	'Value', Atomdata(52,[2 4 6 8]));
% config.configParameter('SF_c',...
% 	'Value', Atomdata(52,9));
% config.configParameter('APConst',...
% 	'Value', [0 0 0;...
% 				1/2 1/2 1/2]);
% config.configParameter('APFitPattern',...
% 	'Value', [0 0 0;...
% 				0 0 0]);
% config.configParameter('APFitParams',...
% 	'Value', 0);
% config.configParameter('AtomCoordCnts',...
% 	'Value', 0);

%% FitParameter for the FWHM and the line position calibration
config.configParameter('FluorScaleFactor_K',...
	'Value', 1,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorScaleFactor_L',...
	'Value', 1,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', true);
config.configParameter('FluorDeltaEnergy_K',...
	'Value', zeros(3,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorDeltaEnergy_L',...
	'Value', zeros(3,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorU_K',...
	'Value', 0.0025,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorW_K',...
	'Value', 0.0005,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorU_L',...
	'Value', 0.0025,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorW_L',...
	'Value', 0.0005,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);

%% Escape peaks
% config.configParameter('EscapeInt_Alpha',...
% 	'Value', ones(3,1));
% config.configParameter('EscapeInt_Beta',...
% 	'Value', ones(3,1));
% config.configParameter('EscapeAlphaInd',...
% 	'Value', [2; 3; 4]);
% config.configParameter('EscapeBetaInd',...
% 	'Value', [2; 3; 4]);
% config.configParameter('EscapeScaleFactor_Alpha',...
% 	'Value', 1,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeScaleFactor_Beta',...
% 	'Value', 1,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeU_Alpha',...
% 	'Value', 0.0025,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeU_Beta',...
% 	'Value', 0.0005,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeW_Alpha',...
% 	'Value', 0.0025,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeW_Beta',...
% 	'Value', 0.0005,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);

%% Phase
config.configParameter('ScaleFactor',...
	'Value', 1,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', true);
config.configParameter('StructureFactor',...
	'Value', ones(7,1).*100,...
	'SpecIndex', 1:22,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StructureFactor',...
	'Value', ones(6,1).*100,...
	'SpecIndex', 23:25,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StructureFactor',...
	'Value', ones(5,1).*100,...
	'SpecIndex', 26,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StructureFactor',...
	'Value', ones(5,1).*100,...
	'SpecIndex', 27,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StructureFactor',...
	'Value', ones(4,1).*100,...
	'SpecIndex', 28:29,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DeltaEnergy_a',...
	'Value', -0.0268,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DeltaEnergy_b',...
	'Value',  0.0028,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DeltaEnergy_c',...
	'Value', -3.4234e-005,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('LatticeParam1',...
	'Value', 2.865,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('LatticeParam2',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('LatticeParam3',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StressCoef',...
	'Value', [-500; -60; 0.5],...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('P_Size',...
	'Value', 0.0392,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('U_Strain',...
	'Value', 3.1171e-005,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('V_Detector',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('X_Size',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('Y_Strain',...
	'Value', 8.7785e-004,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('Z_Detector',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('Background',...
	'Value', zeros(6,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', true);

% out = fitter.executeFit(rc);>>>>>>> .r49
