classdef EnergyCalibCorr < rietveld.func.spec.corr.EnergyCalibCorrInterface
	
	methods (Access = public)
		
		function X = execute(obj, X, ~, ~, ~, spec)
			
			deltaEabc = polyval([spec.DeltaEnergy_c, spec.DeltaEnergy_b, spec.DeltaEnergy_a], X);
			X = X - deltaEabc;
		end
		
		function obj = addFunctionParameters(obj, pc)
			
			obj.addParameter(pc, 'DeltaEnergy_a',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'DeltaEnergy_b',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'DeltaEnergy_c',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', true);
		end		
	end
	
	methods (Access = protected)
		
		function obj = initSubFunctions(obj)
		end
	end	
end