function y = LayerThicknessFunction( beta, layer , tau)
%LAYERTHICKNESSFCUNTION Summary of this function goes here
%   Detailed explanation goes here
        y = beta(1) + (beta(2)-beta(1)).*exp(-layer(2)./tau); % + ...
%             (beta(3)-beta(2)).*exp(-layer(3)./tau) + ...
%             (beta(4)-beta(3)).*exp(-layer(4)./tau);% + ...
% %             (beta(5)-beta(4)).*exp(-layer(5)./tau);% + ...
% %             12.*exp(-layer(6)./tau);

% y = beta(1).*heaviside(tau-layer(1)) + ...
%     (beta(2)-beta(1)).*heaviside(tau-layer(2)); % + ...
%     (beta(3)-beta(2)).*heaviside(tau-layer(3)) + ...
%     (beta(4)-beta(3)).*heaviside(tau-layer(4));% + ...
%     (beta(5)-beta(4)).*heaviside(tau-layer(5));% + ...
%     (beta(6)-beta(5)).*heaviside(tau-layer(6));

end

