%% Choice of diffractometer, 1 = EDDI, 2 = LEDDI (calculation of tau is modified)
config.configParameter('Diffractometer',...
	'Value', 1);
%% If "Diffractometer" == 2, choice of Measurement Mode, 1 = Mode-I, 2 = Mode-II
config.configParameter('Mode',...
	'Value', 1);
%% If "Diffractometer" == 2, choice of detector, 1 = Det1 (rausgefahren), 2 = Det2 (Primaerstrahl)
config.configParameter('Detector',...
	'Value', 1);
%% Number of specs used in the evaluation
NumberofSpecs = 1;
%% Choice of scattering angle TwoTheta
config.configParameter('TwoTheta',...
	'Value', 14,...
	'LowerConstraint', 12,...
	'UpperConstraint', 16,...
	'Refinable', false);

config.configParameter('LowerChannelBound',...
	'Value', 'Enter Value');

config.configParameter('UpperChannelBound',...
	'Value', 'Enter Value');

% Enter E-positions of dummy peaks

Pos = [33.08; 37.83; 38.77];

config.configParameter('DummyIntensity',...
	'Value', 1000*ones(length(Pos),1),...
	'LowerConstraint', 0,...
	'UpperConstraint', 1000000,...
	'Refinable', false);

config.configParameter('DummyMixingFactor',...
	'Value', 0.5*ones(length(Pos),1),...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);

config.configParameter('DummyPosition',...
	'Value', Pos,...
	'LowerConstraint', Pos - 0.2,...
	'UpperConstraint', Pos + 0.2,...
	'Refinable', false);

config.configParameter('DummyWidth',...
	'Value', 0.2*ones(length(Pos),1),...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);

% Enter psi angles of measurement (automatically)
psiTmp = round(S.Psi);
for i = 1:numberOfSpecs
	config.configParameter('Psi',...
		'Value', psiTmp(i),...
		'SpecIndex', i);
end

%% Input of photon energies of principal K-, L-shell emmision lines
config.configParameter('FluorPos_K',...
	'Value', [33.034; 33.442; 37.801]);
config.configParameter('FluorPos_L',...
	'Value', 38.74);
config.configParameter('FluorInt_K',...
	'Value', [0.55; 1.00; 0.35]);
config.configParameter('FluorInt_L',...
	'Value', 1);

%% Input of the h k l values and multiplicity m values
% Enter hkl and multiplicity values of material
hklTmp = [1 0 0 6;...
		1 1 0 12;...
		1 1 1 8;...
		2 0 0 6;...
		2 1 0 24;...
		2 1 1 24;...
		2 2 0 12;...
% 		2 2 1 24;...
		3 0 0 6;...
% 		3 1 0 24;...
		3 1 1 24;...
% 		2 2 2 8;...
% 		3 2 0 24;...
		3 2 1 48;...
% 		4 0 0 6;...
% 		3 2 2 24;...
		4 1 0 24;...
% 		3 3 0 12;...
		4 1 1 24;...
% 		3 3 1 24;...
% 		4 2 0 24;...
		4 2 1 48];...
% 		3 3 2 24;...
% 		4 2 2 24;...
% 		4 3 0 24;...
% 		5 0 0 6;...
% 		5 1 0 24];...
% 		4 3 1 48;...
% 		5 1 1 24];

config.configParameter('H',...
	'Value', hklTmp(:,1));
config.configParameter('K',...
	'Value', hklTmp(:,2));
config.configParameter('L',...
	'Value', hklTmp(:,3));

config.configParameter('Multiplicity',...
	'Value', hklTmp(:,4));

config.configParameter('Alpha',...
	'Value', 90);
config.configParameter('Beta',...
	'Value', 90);
config.configParameter('Gamma',...
	'Value', 90);
% Enter d0 values
config.configParameter('d0',...
	'Value', [2.02806442372041; 1.43433425576655; 1.17118571580656; 1.01442209381871; 0.907627099161091; 0.828427343176114; 0.767201013674323]);

config.configParameter('RingCurrent',...
	'Value', 300);

% Define dead time of measurement (automatically)
deadTimeTmp = S.DeadTime;

for i = 1:numberOfSpecs
	config.configParameter('DeadTime',...
		'Value', deadTimeTmp(i),...
		'SpecIndex', i);
end

%% Input of the DEK values
DEK_S_Tmp = [-5.446e-007 2.954e-006;...
		-6.452e-007 3.282e-006;...
		-5.553e-007 2.964e-006;...
		-6.764e-007 2.806e-006;...
		-6.101e-007 3.147e-006;...
		-6.407e-007 3.228e-006;...
		-5.446e-007 2.954e-006;...
% 		-6.138e-007 3.182e-006;...
		-5.740e-007 3.022e-006;...
% 		-5.463e-007 2.941e-006;...
		-5.245e-007	2.939e-006;...
% 		-6.412e-007 3.237e-006;...
% 		-5.553e-007 2.964e-006;...
		-5.751e-007 3.044e-006;...
% 		-6.452e-007 3.282e-006;...
% 		-5.231e-007 2.938e-006;...
		-5.783e-007 3.090e-006;...
% 		-5.553e-007 2.964e-006;...
		-6.887e-007 3.387e-006;...
% 		-5.766e-007 3.034e-006;...
% 		-5.434e-007	2.929e-006;...
		-5.925e-007 3.078e-006];...
% 		-5.885e-007 3.101e-006;...
% 		-5.537e-007 3.015e-006;...
% 		-4.764e-007 2.806e-006;...
% 		-5.404e-007 2.928e-006;...
% 		-6.101e-007 3.147e-006];...
% 		-5.295e-007 2.889e-006;...
% 		-6.324e-007 3.241e-006];
	
config.configParameter('DEK_S1',...
	'Value', DEK_S_Tmp(:,1));
config.configParameter('DEK_S2',...
	'Value', DEK_S_Tmp(:,2));

%% Input of the attenuation factors
config.configParameter('DensityAir',...
	'Value', 1.2041e-003);
load(fullfile(rvpath,'data','Physics','Air_Absorption.mat'));
config.configParameter('X_airabsorption',...
	'Value', X_airabsorption);
config.configParameter('Y_airabsorption',...
	'Value', Y_airabsorption_en);
config.configParameter('DetectorDistance',...
	'Value', 110);

%% material absorption correction
config.configParameter('Density',...
	'Value', 4.711);
load(fullfile(rvpath,'data','Physics','LaB6_absorption_XCOM'));
config.configParameter('X_abs',...
	'Value', X_abs);
config.configParameter('Y_abs',...
	'Value', Y_abs);

%% structure factor calculation
load(fullfile(rvpath,'data','Physics','AtomSF.mat'))
% Input of the atom form factor parameter
config.configParameter('SF_a',...
	'Value', Atomdata(170,[1 3 5 7]));
config.configParameter('SF_b',...
	'Value', Atomdata(170,[2 4 6 8]));
config.configParameter('SF_c',...
	'Value', Atomdata(170,9));
% % Input of the atom coordinates
% config.configParameter('APConst',...
% 	'Value', [0 0 0;...
% 			  0 1/2 1/2;...
% 			  1/2 0 1/2;...
% 			  1/2 1/2 0]);
% % Input of the fit pattern to declare which atom coordinates are refinable 
% % (0 = constant, 1 = refinable, -1 = negative of coordinate)
% config.configParameter('APFitPattern',...
% 	'Value', [0 0 0;...
% 			  0 0 0;...
% 			  0 0 0;...
% 			  0 0 0]);
% % Input of the start value of the refinable atom coordinate
% config.configParameter('APFitParams',...
% 	'Value', 0,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', 1,...
% 	'Refinable', false);
% % Input of the atom coordinate count, that describes how many atom 
% % coordinates per atom exist
% config.configParameter('AtomCoordCnts',...
% 	'Value', 4);
% % Input of anomalous scattering factors
% load(fullfile(rvpath,'data','Physics','anomalousScattering','Auf1.mat'))
% load(fullfile(rvpath,'data','Physics','anomalousScattering','Auf2.mat'))
% config.configParameter('Atom1f1',...
% 	'Value', Auf1);
% config.configParameter('Atom1f2',...
% 	'Value', Auf2);
% config.configParameter('Atom2f1',...
% 	'Value', 0);
% config.configParameter('Atom2f2',...
% 	'Value', 0);
% % Input of the Debye-Waller factor
% config.configParameter('DebyeWaller',...
% 	'Value', 0,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);


% Input of the atom positions of the respective atom
% Positons of atom 1, where "1" desribes the position which is variable
% Constant atom positions (the variable positions are also written into the 
% matrix)
AP1Const = [0 0 0; 0 1/2 1/2; 1/2 0 1/2; 1/2 1/2 0];
% Position of the atom which needs to be "corrected" (no. 1)
APosAP1 = [0 0 0; 0 0 0; 0 0 0; 0 0 0];
% Positons of atom 2, where "2,3" desribes the position which is variable
% Constant atom positions (the variable positions are also written into the 
% matrix)
% AP2Const =[1 1/2 1/2; -1 1/2 1/2; 1/2 1 1/2; 1/2 -1 1/2; 1/2 1/2 1; 1/2 1/2 -1];
% Position of the atom which needs to be "corrected" (no. 2)
% APosAP2 = [0 0 0; 0 0 0; 0 0 0; 0 0 0; 0 0 0; 0 0 0];
% Input of the symmetry operators ("AP1" + SO...)
SO = [0 0 0];

% Create the matrix with all atom positions of all atoms (from AP1 and AP2)
config.configParameter('APConst',...
	'Value', repmat(AP1Const,size(SO,1),1));

% Input of the fit pattern to declare which atom coordinates are refinable 
% (0 = constant, 1(2,3) = refinable, -1(-2,-3) = negative of coordinate)
% A APFitPattern needs to be created for each atom.
APFitPattern1 = [0 0 0];
% APFitPattern2 = [1 0 0; -1 0 0; 0 1 0; 0 -1 0; 0 0 1; 0 0 -1];

config.configParameter('APFitPattern',...
	'Value', repmat(APFitPattern1,size(SO,1),1));
% Input of the start value of the refinable atom coordinate
config.configParameter('CountAPFitParams',...
	'Value', 0);
% config.configParameter('APFitParam1',...
% 	'Value', 0,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', 1,...
% 	'Refinable', false);
% config.configParameter('APFitParam2',...
% 	'Value', 0,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', 1,...
% 	'Refinable', false);
% config.configParameter('APFitParam3',...
% 	'Value', 0,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', 1,...
% 	'Refinable', false);
% config.configParameter('APFitParam4',...
% 	'Value', 0,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', 1,...
% 	'Refinable', false);
% config.configParameter('APFitParam5',...
% 	'Value', 0,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', 1,...
% 	'Refinable', false);
% config.configParameter('APFitParam6',...
% 	'Value', 0,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', 1,...
% 	'Refinable', false);

% Input of correction factors for the atom positions in AP1 and AP2 etc.
% The number of parameters needs to be the same as the numbers of
% APFitParams, due to the for-loop. That's why there is a "0".
config.configParameter('APosParam',...
	'Value', 0,...
	'Refinable', false);
% Create the matrix with the atom positions that need to be corrected for
% the APosParam.
config.configParameter('APosPattern',...
	'Value', repmat(APosAP1,size(SO,1),1));

config.configParameter('AtomCoordinates',...
	'Value', repmat(SO(1,:),size(APosAP1,1),1));
% Input of the atom coordinate count, that describes how many atom 
% coordinates per atom exist
config.configParameter('AtomCoordCnts',...
	'Value', 1);
% Input of anomalous scattering factors
load(fullfile(rvpath,'data','Physics','anomalousScattering','Auf1.mat'))
load(fullfile(rvpath,'data','Physics','anomalousScattering','Auf2.mat'))
config.configParameter('Atom1f1',...
	'Value', Auf1);
config.configParameter('Atom1f2',...
	'Value', Auf2);
% Input of the Debye-Waller factors (one for each atom, if less than 3
% atoms present, the other ones have to be set to zero.)
config.configParameter('DebyeWaller1',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DebyeWaller2',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DebyeWaller3',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);

%% FitParameter for the FWHM and the line position calibration
config.configParameter('FluorScaleFactor_K',...
	'Value', 1,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorScaleFactor_L',...
	'Value', 1,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorDeltaEnergy_K',...
	'Value', zeros(3,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorDeltaEnergy_L',...
	'Value', zeros(3,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorU_K',...
	'Value', 0.0025,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorW_K',...
	'Value', 0.0005,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorU_L',...
	'Value', 0.0025,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('FluorW_L',...
	'Value', 0.0005,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);

%% Escape peaks
% config.configParameter('EscapeInt_Alpha',...
% 	'Value', ones(4,1));
% config.configParameter('EscapeInt_Beta',...
% 	'Value', ones(4,1));
% config.configParameter('EscapeAlphaInd',...
% 	'Value', [1; 2; 3; 4]);
% config.configParameter('EscapeBetaInd',...
% 	'Value', [1; 2; 3; 4]);
% config.configParameter('EscapeScaleFactor_Alpha',...
% 	'Value', 1,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeScaleFactor_Beta',...
% 	'Value', 1,...
% 	'LowerConstraint', 0,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeU_Alpha',...
% 	'Value', 0.0025,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeU_Beta',...
% 	'Value', 0.0005,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeW_Alpha',...
% 	'Value', 0.0025,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);
% config.configParameter('EscapeW_Beta',...
% 	'Value', 0.0005,...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);

%% Phase
NumberOfPeaks = length(hklTmp);
config.configParameter('ScaleFactor',...
	'Value', 1,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', true);

config.configParameter('StructureFactor',...
	'Value', ones(NumberOfPeaks,1).*500,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);

config.configParameter('DeltaEnergy_a',...
	'Value', 0,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DeltaEnergy_b',...
	'Value', 0,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('DeltaEnergy_c',...
	'Value', 0,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);

config.configParameter('LatticeParam1',...
	'Value', 4.15689,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('LatticeParam2',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('LatticeParam3',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
% config.configParameter('StressCoef',...
% 	'Value', [0; 0; 0],...
% 	'LowerConstraint', -Inf,...
% 	'UpperConstraint', +Inf,...
% 	'Refinable', false);

config.configParameter('sigmatau',...
	'Value', zeros(NumberOfPeaks,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);

config.configParameter('StressCoef1',...
	'Value', 0,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StressCoef2',...
	'Value', 0,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);
config.configParameter('StressCoef3',...
	'Value', 0,...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);

config.configParameter('epsilon',...
	'Value', zeros(NumberOfPeaks,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', false);

config.configParameter('P_Size',...
	'Value', 0.00276603932,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('U_Strain',...
	'Value', 0.00001241635,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('V_Detector',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('X_Size',...
	'Value', 0.00005,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('Y_Strain',...
	'Value', 0.00024437191,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('Z_Detector',...
	'Value', 0,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
% Define parameters of 
config.configParameter('PVmix',...
	'Value', ones(NumberOfPeaks,1)*0.5,...
	'LowerConstraint', 0,...
	'UpperConstraint', 1,...
	'Refinable', false);
config.configParameter('FWHM',...
	'Value', ones(NumberOfPeaks,1)*0.25,...
	'LowerConstraint', 0.001,...
	'UpperConstraint', 1,...
	'Refinable', false);
% Initial number of background parameters
config.configParameter('Background',...
	'Value', zeros(4,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', true);
% If two separate BKG functions are used, define the channel range in which
% each function is applied
config.configParameter('BkgRange',...
	'Value', [1;999;1000;8851],...
	'LowerConstraint', 0,...
	'UpperConstraint', 100000,...
	'Refinable', false);
% Initial number of background parameters for BKG function 1
config.configParameter('Background1',...
	'Value', zeros(4,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', true);
% Initial number of background parameters for BKG function 2
config.configParameter('Background2',...
	'Value', zeros(4,1),...
	'LowerConstraint', -Inf,...
	'UpperConstraint', +Inf,...
	'Refinable', true);
% Define background parameters for BKG function "Asym. Double Sigmoid"
config.configParameter('MaxAmp',...
	'Value', [30; 55],...
	'LowerConstraint', 0,...
	'UpperConstraint', Inf,...
	'Refinable', false);
config.configParameter('Center',...
	'Value', [14; 48],...
	'LowerConstraint', 0,...
	'UpperConstraint', Inf,...
	'Refinable', false);
config.configParameter('Width',...
	'Value', [8; 29],...
	'LowerConstraint', 0,...
	'UpperConstraint', Inf,...
	'Refinable', false);
config.configParameter('Shape1',...
	'Value', [3.2; 4.8],...
	'LowerConstraint', 0,...
	'UpperConstraint', Inf,...
	'Refinable', false);
config.configParameter('Shape2',...
	'Value', [3.3; 7.9],...
	'LowerConstraint', 0,...
	'UpperConstraint', Inf,...
	'Refinable', false);

% out = fitter.executeFit(rc);