classdef DummyPV < rietveld.func.spec.dummy.DummyInterface

	methods (Access = public)
		
		function Y = execute(obj, X, ~, ~, ~, spec)
			
			Y = 0;
			
			for i = 1:length(spec.SinglePeakPVPos)
				Y = Y + spec.SinglePeakPVInt(i) .* (spec.SinglePeakPVmix(i) .* exp(-(X - spec.SinglePeakPVPos(i)).^2/(2.*spec.SinglePeakPVsigma(i).^2)) + ...
					(1 - spec.SinglePeakPVmix(i)) .* (1 + 4 * ((X - spec.SinglePeakPVPos(i))/spec.SinglePeakPVsigma(i)).^2).^(-1));				
			end
		end
		
		function obj = addFunctionParameters(obj, pc)
			
			obj.addParameter(pc, 'SinglePeakPVInt',...
				'Category', 'Dummy peaks',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true,...
				'Value', []);
			obj.addParameter(pc, 'SinglePeakPVPos',...
				'Category', 'Dummy peaks',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true,...
				'Value', []);
			obj.addParameter(pc, 'SinglePeakPVsigma',...
				'Category', 'Dummy peaks',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true,...
				'Value', []);
			obj.addParameter(pc, 'SinglePeakPVmix',...
				'Category', 'Dummy peaks',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true,...
				'Value', []);
		end
	end
	
	methods (Access = protected)
		
		function obj = initSubFunctions(obj)
		end
	end
end

