%% (* Plot the current measurement data for the search and match routine *)
%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
% Choose "true" if the x-data should be keV
P.XInUnit = true;
% Clean up all temporary variables
P.CleanUpTemporaryVariables = false;

% Load Data base for search and match. Peformed only once at the beginning.
if ~evalin('base','exist(''PDFDataBasesorted'',''var'')')  
    disp('PCPDF Database is being loaded...this takes some time.')
    load(fullfile('Data','PCPDFdatabase','PCPDFDataBaseSorted.mat'))
end
%% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
T.Figure = figure('Toolbar', 'figure','units','normalized',...
    'OuterPosition',[0.125 0.125 0.75 0.75]);
% Create plothandles to share data between callbacks.
Plothandles = guihandles(T.Figure);
Plothandles.PopupValue = 0;
Plothandles.table = 0;
Plothandles.tableSaM = 0;
Plothandles.ResultSaM = cell(1,1);
Plothandles.IndexHitCount = 0;
Plothandles.filtercheckbox = 0;
Plothandles.filtercheckbox1 = 0;
Plothandles.tableFilter = 0;
Plothandles.filterElementedit = 0;
Plothandles.filterCrystalSystemopoup = 0;
Plothandles.PopupValueFilter = 0;
Plothandles.checkboxplot = 0;
Plothandles.PDFPlots = 0;
Plothandles.matchedit = 0;
Plothandles.Yrawdata = 0;
% Daten fuer das Slider-Callback
T.Plots = zeros(length(Measurement),1);
T.Title = cell(length(Measurement),1);
hold on;

% TwoTheta of the measurement.
T.twotheta = Measurement(1).twotheta;
Plothandles.TwoTheta = T.twotheta;

% Calculation of the maximum peak intensities of the respecive spectrum
T.Peaks_y = zeros(length(Measurement),1);
% Find intensity maximum
for i = 1:length(Measurement)
    T.Peaks_y(i,:) = max(DataTmp{i}(:, 2));
end
% position of plot window
T.positionVector1 = [0.065, 0.15, 0.75, 0.75]; 	

% Plot of measurement data.
for c = 1:length(Measurement)
    if (P.XInUnit)
        T.Plots(c) = plot(DataTmp{c}(:, 1), DataTmp{c}(:, 2));
        T.Title{c} = ['Measurment Data for ', Measurement(c).Name];
        ax = gca;
        datacursormode on
        box(ax, 'on');
        ax.Position = T.positionVector1;
        set(T.Plots(c,1), 'Color', 'blue');
        xlabel('Energy [keV]');
        ylabel('Intensity [cts]');
    else
        T.Plots(c) = plot(1:length(DataTmp{c}(:, 1)), DataTmp{c}(:, 2));
        T.Title{c} = ['Measurment Data for ', Measurement(c).Name];
        xlabel('Channels [no unit]');
        ylabel('Intensity [cts]');
    end
end

if length(Measurement) == 1
    Min = 0;
    Max = length(Measurement);
    SliderStep = [1 1];
else
    Min = 1;
    Max = length(Measurement);
    SliderStep = [1/(length(Measurement)-1) 1/(length(Measurement)-1)];
end

% Create Slider object.
T.Slider = uicontrol(...
        'Style','slider',...
        'Tag','Slider',...
        'Parent',T.Figure,...
        'Units','normalized',...
        'Position', [0.3875 0.05 0.1 0.03],...
        'Min',Min,...
        'Max',Max,...
        'SliderStep',SliderStep,...
        'Value',1,...
        'Callback',{@SliderCallback,T});
    
SliderCallback(T.Slider, 0, T);
%% GUI - Search and Match routine
% The following objects define the GUI of the search and match routine.
%% GUI - Table with peak data for search and match
% Uipanel to store table with peak positions. The peak positions are
% defined using data tips created with the Matlab Data Cursor. The peaks
% have to ba saved as 'Peaks' to the matlab workspace.
tablepanel = uipanel('Title', 'Peak data for Search and Match',...
    'Parent',T.Figure,...
    'Units','normalized',...
    'Position', [0.827 0.658 0.15 0.25]);
% Create table with peak positions. The table contains checkboxes to choose
% which peak should be concidered in the search and match.
table  = uitable('Units','normalized',...
    'Tag','table',...
    'Position', [0.055 0.205 0.89 0.785],...
    'Parent',tablepanel,...
    'ColumnName', {'Energy', 'Search'},...
    'ColumnWidth', {115 85},...
    'ColumnFormat',[{[]},'logical'],...
    'ColumnEditable', [false true],...
    'Data', [num2cell(zeros(1,1)), num2cell(true(1,1))],...
    'CellEditCallback', {@table_CellEditCallback});
    s = sprintf('Select peaks to be included in the\nSearch and Match by checking\nthe ''Search'' checkbox.');
    table.TooltipString = s;
% Load peak positions by pressing the 'Load Peak Data' button.
loadbutton = uicontrol('Style','pushbutton',...
    'String','Load Peak Data',...
    'Units','normalized',...
    'Tag', 'loadbutton',...
    'Position',[0.25 0.03 0.5 0.125],...
    'Parent',tablepanel,...
    'Callback',{@loadbutton_Callback, table});
    s = sprintf('Select peaks using the\nData Cursor tool from\nMatlab. Export data tips\nand save as ''Peaks''.');
    loadbutton.TooltipString = s;

%% GUI - Search and Match routine
% A tab group is created. In the first tab the search and match is 
% performed. In the second tab the results are processed.
% Create Tab group.
tgroup = uitabgroup('Parent', T.Figure,...
    'Units','normalized',...
    'Position', [0.827 0.29 0.15 0.35],...
    'SelectionChangedFcn', {@tabChanged_Callback});
% Define two tabs.
tab1 = uitab('Parent', tgroup, 'Title', 'Search and Match');
tab2 = uitab('Parent', tgroup, 'Title', 'Results');
%% Information and calculations for tab1 - Search and Match routine.
    % Text explaining the use of the tolerance value.
    texttol1 = uicontrol('Style', 'text',...
        'Parent', tab1,...
        'Units','normalized',...
        'Position', [0.025 0.875 0.975 0.1],...
        'String', sprintf('The peaks are matched according to (abs(Peak_db - Peak_meas)) <= tol.'),...
        'FontSize', 9,...
        'HorizontalAlignment', 'left');
    texttol2 = uicontrol('Style', 'text',...
        'Parent', tab1,...
        'Units','normalized',...
        'Position', [0.125 0.675 0.5 0.15],...
        'String', sprintf('Set tolerance value'),...
        'FontSize', 9,...
        'HorizontalAlignment', 'left');
    texttol3 = uicontrol('Style', 'text',...
        'Parent', tab1,...
        'Units','normalized',...
        'Position', [0.558 0.723 0.5 0.1],...
        'String', 'tol =',...
        'FontSize', 10,...
        'FontWeight', 'bold',...
        'HorizontalAlignment', 'left');
    s = sprintf('Enter tolerance value. A large\nvalue gives more results.');
    texttol3.TooltipString = s;
    toledit  = uicontrol('Style','edit','String','0.001',...
        'Units','normalized',...
        'Tag', 'toledit',...
        'Position',[0.6825 0.76 0.275 0.075],...
        'Parent',tab1);
    % Text explaining the use of hits.
    texthit1 = uicontrol('Style', 'text',...
        'Parent', tab1,...
        'Units','normalized',...
        'Position', [0.025 0.575 0.975 0.1],...
        'String', sprintf('Consider only results where the number of peak matches >= hits.'),...
        'FontSize', 9,...
        'HorizontalAlignment', 'left');
    texthit2 = uicontrol('Style', 'text',...
        'Parent', tab1,...
        'Units','normalized',...
        'Position', [0.125 0.378 0.4 0.15],...
        'String', sprintf('Set hits value'),...
        'FontSize', 9,...
        'HorizontalAlignment', 'left');
    texthit3 = uicontrol('Style', 'text',...
        'Parent', tab1,...
        'Units','normalized',...
        'Position', [0.535 0.428 0.5 0.1],...
        'String', 'hits =',...
        'FontSize', 10,...
        'FontWeight', 'bold',...
        'HorizontalAlignment', 'left');
    s = sprintf('Enter hits value. A small\nvalue gives more results.\nThe maximum value\nshould equal the number\nof selected peaks.');
    texthit3.TooltipString = s;
    hitedit  = uicontrol('Style','edit','String','10',...
        'Units','normalized',...
        'Tag', 'hitedit',...
        'Position',[0.6825 0.46 0.275 0.075],...
        'Parent',tab1);
    % Show how many matches were found.
    textmatch1 = uicontrol('Style', 'text',...
        'Parent', tab1,...
        'Units','normalized',...
        'Position', [0.475 0.0725 0.5 0.1],...
        'String', 'Matches found',...
        'FontSize', 10,...
        'FontWeight', 'bold',...
        'HorizontalAlignment', 'left');
    matchedit  = uicontrol('Style','edit',...
        'String','no',...
        'Units','normalized',...
        'Tag', 'matchedit',...
        'Position',[0.125 0.1 0.3 0.1],...
        'Parent',tab1);
    % Search database button. Explanation in the callback function.
    searchbutton = uicontrol('Style','pushbutton','String',...
        'Search Database',...
        'Units','normalized',...
        'Tag', 'searchbutton',...
        'Position',[0.125 0.28 0.75 0.1],...
        'Parent',tab1,...
        'Callback',{@searchbutton_Callback, table, toledit, hitedit, matchedit});
%% Information and calculations for tab2 - Process results.
    % Create table with peak information. The table contains all matches
    % from the search and match.
    tableSaM  = uitable('Units','normalized',...
        'FontSize',8,...
        'Tag','table',...
        'Position', [0.055 0.2 0.89 0.728],...
        'Parent',tab2,...
        'ColumnName', {'Plot','PDFCardNumber','ElementSymbol','ElementName','spaceGroupSymbol','spaceGroupNumber'},...
        'ColumnWidth', {30 50 50 50 50 50},...
        'ColumnFormat',['logical',{[]}],...
        'ColumnEditable', [true false false false false false false false],...
        'Data', [num2cell(false(1,1)), num2cell(zeros(1,1)), num2cell(zeros(1,1)), num2cell(zeros(1,1)), num2cell(zeros(1,1)), num2cell(zeros(1,1))],...
        'CellEditCallback', {@tableSaM_CellEditCallback});
    % Filter options button. This button opens a new window where the user
    % can filter the results according to element, name and crystal system.
    filterbutton = uicontrol('Style','pushbutton',...
        'String','Filter options',...
        'Units','normalized',...
        'Tag', 'filterbutton',...
        'Position',[0.05 0.05 0.44 0.1],...
        'Parent',tab2,...
        'Callback',{@filterbutton_Callback, T.Figure, matchedit});
    % Plot button. This button plots the energy positions of the phase(s)
    % selected by the user via the checkboxes in the table.
    plotpdfbutton = uicontrol('Style','pushbutton',...
        'String','Plot',...
        'Units','normalized',...
        'Tag', 'plotbutton',...
        'Position',[0.505 0.05 0.235 0.1],...
        'Parent',tab2,...
        'Callback',{@plotpdfbutton_Callback, T.Figure, tableSaM});
    s = sprintf('Select phase(s) to be\nplotted by checking\nthe checkbox.');
    plotpdfbutton.TooltipString = s;
    % Clear button. This button clears the plot(s) selected by the user
    % via the checkboxes in the table.
    clearpdfbutton = uicontrol('Style','pushbutton',...
        'String','Clear',...
        'Units','normalized',...
        'Tag', 'clearbutton',...
        'Position',[0.75 0.05 0.2 0.1],...
        'Parent',tab2,...
        'Callback',{@clearpdfbutton_Callback, T.Figure, tableSaM});
    s = sprintf('Select plot(s) to be deleted\nby unchecking the checkbox.');
    clearpdfbutton.TooltipString = s;


%% GUI - Plot fluorescence lines
% The following components create the GUI panel "Plot of fluorescence
% lines. The panel consists of a popup menu where all elements are listed,
% and two buttons, one to plot the fluorescence lines and one to reset
% (clear) the plotted data.
% Path of the fluorescence line file
fid = fopen(fullfile('Data','Materials','Fluorescence_Lines.dat'));
% Einlesen der Datei und speichern in einem Cell-Array
% Spaltennamen lauten:
% No.;Element;Ka1;Ka2;Kb1;La1;La2;Lb1;Lb2;Lg1
T.FluorCellArray = textscan(fid,'%d %s %f %f %f %f %f %f %f %f',...
    'headerlines',1, 'delimiter','\t');
% String Vektor mit Elementnamen erzeugen, für PopUpMenu
ElementsString = T.FluorCellArray{1,2}(:,1);
% Uipanel components for plotting fluorescence lines
    % Uipanel
    hpanel = uipanel('Title', 'Plot of fluorescence lines',...
        'Units','normalized',...
        'Position', [0.827 0.1475 0.15 0.125]);
    % Reset button
    hreset = uicontrol('Style','pushbutton','String','Reset Data',...
        'Units','normalized',...
        'Tag', 'hreset',...
        'Position',[0.15 0.075 0.7 0.25],...
        'Parent',hpanel,...
        'Callback',{@resetbutton_Callback});
    % Plot button
    hplot = uicontrol('Style','pushbutton','String','Plot fluorescence lines',...
        'Units','normalized',...
        'Tag', 'hplot',...
        'Position',[0.15 0.375 0.7 0.25],...
        'FontSize', 8,...
        'Parent',hpanel,...
        'Callback',{@plotbutton_Callback, T});
    % Popup menu title
    htext2 = uicontrol('Style','text','String','Select Element',...
        'Parent',hpanel,...
        'Tag', 'htext2',...
        'Units','normalized',...
        'Position',[0.151 0.65 0.7 0.225],...
        'HorizontalAlignment', 'left');
    % Popup menu
    hpopup = uicontrol('Style','popupmenu',...
        'String',ElementsString,...
        'Tag', 'hpopup',...
        'Units','normalized',...
        'Position',[0.586 0.7 0.25 0.225],...
        'Parent',hpanel,...
        'Callback',{@popup_menu_Callback});

Plothandles.table = table;
Plothandles.tableSaM = tableSaM;
Plothandles.matchedit = matchedit;
Plothandles.Yrawdata = T.Peaks_y;
guidata(T.Figure,Plothandles);
if (P.CleanUpTemporaryVariables)
    clear('P');
    clear('T');
    clear c;
end
%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++