% Diese Methode exportiert das Auswertungs-Objekt als PSI-File, um damit in
% Mathematica weiterarbeiten zu kˆnnen
% Input: Filename, Dateiname (ohne Endung), string|va /
% Output: none
function SaveToPsiFileNew(DiffractionLines,Filename,FileName,FitFunc,SpecFileCheck)

%% (* Stringenzpr¸fung *)
    validateattributes(Filename,{'char'},{'row'});

%% (* Vorbereitung *)
    %Pfad bilden
    Path = Filename;
    %Datei erzeugen
    fid = fopen(Path,'w');
    %DL als Vektor (Abk¸rzung)
    DL = DiffractionLines;
    %Measurement mode
    assignin('base','DiffractionLines',DL)

if FitFunc == 2 || FitFunc == 4 || FitFunc == 5
   %PV-Func        %Gauss          %Lorentz
%% (* Kopf hinzuf¸gen *)
    if SpecFileCheck == 1
        %Datei-Name
        fprintf(fid,'Dateiname: %s.\n\n',FileName);
        %Spalten
        fprintf(fid,['LNr\t',...
            'Emax\t',...
            'dEmax\t',...
            'Iint\t',...
            'Ib\t',...
            'tth\t',...
            'phiP\t',...
            'psiP\t',...
            'etaP\t',...
            'h\t',...
            'k\t',...
            'l\t',...
            'xdiff\t',...
            'ydiff\t',...
            'zdiff\t',...
            'RT\t',...
            'DT\t',...
            'temp1\t',...
            'temp2\t',...
            'heatrate\t ',...
            'time','\n\n']);
%         fprintf(fid,['LNr     ',...
%             'Emax   ',...
%             'dEmax    ',...
%             'Iint      ',...
%             'Ib      ',...
%             'tth     ',...
%             'phiP   ',...
%             'psiP   ',...
%             'etaP  ',...
%             'h   ',...
%             'k   ',...
%             'l   ',...
%             'xdiff   ',...
%             'ydiff   ',...
%             'zdiff   ',...
%             'RT  ',...
%             'DT   ',...
%             'temp1   ',...
%             'temp2   ',...
%             'heatrate    ',...
%             'time','\n\n']);
    else
        %Datei-Name
        fprintf(fid,'Dateiname: %s.\n\n',FileName);
        %Spalten
        fprintf(fid,['LNr\t',...
            'Emax\t',...
            'dEmax\t',...
            'Iint\t',...
            'Ib\t',...
            'tth\t',...
            'phiP\t',...
            'psiP\t',...
            'etaP\t',...
            'h\t',...
            'k\t',...
            'l\t',...
            'xdiff\t',...
            'ydiff\t',...
            'zdiff\t'...
            '\n\n']);
    end
%% (* Daten eintragen *)
    %--> Durchlaufen aller Peaks
    for i_c = 1:size(DL,1)
        % Peak-Infos
        if SpecFileCheck == 1
            fprintf(fid,'%d.\t%.3f\t%.4f\t%.2f\t%.4f\t%.2f\t%.2f\t%.2f\t%.3f\t%d\t%d\t%d\t%.4f\t%.4f\t%.4f\t%.2f\t%.2f\t%.1f\t%.1f\t%.2f\t%s\n',...
                DL(i_c,1:20),datestr(DL(i_c,21),'dd-mm-yyyy-HH-MM-SS'));
%             fprintf(fid,'  %d.  %.3f  %.4f  %d  %.4f  %.2f  %.2f  %.2f  %.3f  %d  %d  %d  %.4f  %.4f  %.4f  %.2f  %.2f  %.1f  %.1f  %.2f  %s\n',...
%                 DL(i_c,1:20),datestr(DL(i_c,21),'dd-mm-yyyy-HH-MM-SS'));
        else
            fprintf(fid,'%d.\t%.3f\t%.4f\t%.2f\t%.4f\t%.2f\t%.2f\t%.2f\t%.3f\t%d\t%d\t%d\t%.4f\t%.4f\t%.4f\n',...
                DL(i_c,1:15));
        end
    end
elseif FitFunc == 3 %TCH-Func
%% (* Kopf hinzuf¸gen *)
    if SpecFileCheck == 1
        %Datei-Name
        fprintf(fid,'Dateiname: %s.\n\n',FileName);
        %Spalten
        fprintf(fid,['LNr\t',...
            'Emax\t',...
            'dEmax\t',...
            'Iint\t',...
            'Ib\t',...
            'FWHM\t',...
            'FWHM_Gauss\t',...
            'FWHM_Lorentz\t',...
            'tth\t',...
            'phiP\t',...
            'psiP\t',...
            'etaP\t',...
            'h\t',...
            'k\t',...
            'l\t',...
            'xdiff\t',...
            'ydiff\t',...
            'zdiff\t',...
            'RT\t',...
            'DT\t',...
            'temp1\t',...
            'temp2\t',...
            'heatrate\t',...
            'time','\n\n']);
    else
        %Datei-Name
        fprintf(fid,'Dateiname: %s.\n\n',FileName);
        %Spalten
        fprintf(fid,['LNr\t',...
            'Emax\t',...
            'dEmax\t',...
            'Iint\t',...
            'Ib\t',...
            'FWHM\t',...
            'FWHM_Gauss\t',...
            'FWHM_Lorentz\t',...
            'tth\t',...
            'phiP\t',...
            'psiP\t',...
            'etaP\t',...
            'h\t',...
            'k\t',...
            'l\t',...
            'xdiff\t',...
            'ydiff\t',...
            'zdiff\t',...
            '\n\n']);
    end
    
%% (* Daten eintragen *)
    %--> Durchlaufen aller Peaks
    for i_c = 1:size(DL,1)
        if SpecFileCheck == 1
            % Peak-Infos
            fprintf(fid,'%d.\t%.3f\t%.4f\t%.2f\t%.4f\t%.4f\t%.4f\t%.2e\t%.2f\t%.2f\t%.2f\t%.2f\t%d\t%d\t%d\t%.1f\t%.2f\t%.2f\t%.4f\t%.4f\t%.4f\t%.4f\t%.4f\t%.4f\t%.1f\t%.1f%.2f\t%s\n',...
                DL(i_c,1:23),datestr(DL(i_c,24),'dd-mm-yyyy-HH-MM-SS'));
        else
            % Peak-Infos
            fprintf(fid,'%d.\t%.3f\t%.4f\t%.2f\t%.4f\t%.4f\t%.4f\t%.2e\t%.2f\t%.2f\t%.2f\t%.2f\t%d\t%d\t%d\t%.1f\t%.2f\t%.2f\t%.4f\t%.4f\t%.4f\t%.4f\n',...
                DL(i_c,1:18));
        end
    end    
end
    %Datei schlieﬂen
    fclose(fid);
end