classdef FluorescenceKL < rietveld.func.spec.fluor.FluorInterface
	
	methods (Access = public)
		
		function Y = execute(obj, X, general, meas, phase, spec)
			
			Y = 0;
			
			% 1 = K, 2 = L
			for i = 1:2
				
				if (i == 1)
					
					FluorPos = phase.FluorPos_K;
					FluorInt = phase.FluorInt_K;
% 					FluorDeltaEnergy = general.FluorDeltaEnergy_K;
					FluorU = general.FluorU_K;
					FluorW = general.FluorW_K;
					FluorScaleFactor = general.FluorScaleFactor_K;
                else
					FluorPos = phase.FluorPos_L;
					FluorInt = phase.FluorInt_L;
% 					FluorDeltaEnergy = general.FluorDeltaEnergy_L;
					FluorU = general.FluorU_L;
					FluorW = general.FluorW_L;
					FluorScaleFactor = general.FluorScaleFactor_L;
				end
% 				disp(FluorPos)
				FluorPos = FluorPos + polyval([spec.DeltaEnergyFluor_c, spec.DeltaEnergyFluor_b, spec.DeltaEnergyFluor_a], FluorPos);
				FluorFWHM = FluorU .* FluorPos + FluorW;
% 				disp(polyval([spec.DeltaEnergyFluor_c, spec.DeltaEnergyFluor_b, spec.DeltaEnergyFluor_a], FluorPos))
				Int = FluorScaleFactor * (FluorInt .*...
					exp(-meas.DensityAir * meas.DetectorDistance * ...
					obj.sfwc.AttenuationCoeffAir.execute(FluorPos, general, meas, phase, spec)));
				
				for j = 1:size(FluorInt, 1)    
					
					Y = Y + Int(j) .* ...
						(2 * sqrt(log(2) / pi) / FluorFWHM(j)) * exp(-4 * log(2) * ((X - FluorPos(j))/FluorFWHM(j)).^2);
				end
			end
		end
		
		function obj = addFunctionParameters(obj, pc)
			
% 			obj.addParameter(pc, 'FluorDeltaEnergy_K',...
% 				'Category', 'Fluorescence',...
% 				'ParamSize', [NaN, 1],...
% 				'Constant', false,...
% 				'PhaseDep', true,...
% 				'SpecDep', true);
% 			obj.addParameter(pc, 'FluorDeltaEnergy_L',...
% 				'Category', 'Fluorescence',...
% 				'ParamSize', [NaN, 1],...
% 				'Constant', false,...
% 				'PhaseDep', true,...
% 				'SpecDep', true);
			obj.addParameter(pc, 'DeltaEnergyFluor_a',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'DeltaEnergyFluor_b',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'DeltaEnergyFluor_c',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'FluorInt_K',...
				'Category', 'Fluorescence',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'FluorInt_L',...
				'Category', 'Fluorescence',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'FluorPos_K',...
				'Category', 'Fluorescence',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'FluorPos_L',...
				'Category', 'Fluorescence',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'FluorU_K',...
				'Category', 'Fluorescence',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'FluorU_L',...
				'Category', 'Fluorescence',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'FluorW_K',...
				'Category', 'Fluorescence',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'FluorW_L',...
				'Category', 'Fluorescence',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'FluorScaleFactor_K',...
				'Category', 'Fluorescence',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'FluorScaleFactor_L',...
				'Category', 'Fluorescence',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', true);
		end
	end
	
	methods (Access = protected)
		
		function obj = initSubFunctions(obj)
			
			obj.addSubFunction('AttenuationCoeffAir', 'rietveld.func.spec.corr.AttenuationCoeffAir',rietveld.func.spec.corr.AttenuationCoeffAir());
		end
	end
end

