classdef TauTwoThetaCorr < rietveld.func.spec.diffpeaks.TauInterface
	
	methods (Access = public)
		
		function tau = execute(obj, acm, ~, meas, phase, spec)
		% acm wird aus Effizienzgruenden direkt uebergeben
			
			tau = (sind(spec.TwoTheta / 2) ./ (2 * phase.Density * acm)) * 10000 * cosd(spec.Psi);
		end

		function obj = addFunctionParameters(obj, pc)

			obj.addParameter(pc, 'TwoTheta',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'Psi',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', true);
			obj.addParameter(pc, 'Density',...
				'Category', 'Material',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', false);
		end
	end
	
	methods (Access = protected)
		
		function obj = initSubFunctions(obj)
		end
	end
	
end