classdef Mod3 < rietveld.func.spec.diffpeaks.strain.StrainInterface

	methods (Access = public)
		
		function eps_hkl = execute(obj, acm, general, meas, phase, spec)
		% acm wird aus Effizienzgruenden direkt uebergeben
			
			tau = obj.sfwc.Tau.execute(acm, general, meas, phase, spec);
			
			sigmatau = phase.StressCoef1./(phase.StressCoef4.*tau + 1) + ...
				phase.StressCoef2.*tau./(phase.StressCoef4.*tau + 1).^2 + ...
				2.* phase.StressCoef3.*tau.^2./(phase.StressCoef4.*tau + 1).^3;
			
			eps_hkl = ((sind(spec.Psi)^2) * general.DEK_S2 + 2 * general.DEK_S1) .* sigmatau;
            
            % Allgemeine Form der Grundgleichung der RSA (sigma33 = 0,
            % sigma12 = 0).
%             sigma11 = phase.Sigma11stressCoef1./(phase.Sigma11stressCoef4.*tau + 1) + ...
% 				phase.Sigma11stressCoef2.*tau./(phase.Sigma11stressCoef4.*tau + 1).^2 + ...
% 				2.* phase.Sigma11stressCoef3.*tau.^2./(phase.Sigma11stressCoef4.*tau + 1).^3;
%             
%             sigma22 = phase.Sigma22stressCoef1./(phase.Sigma22stressCoef4.*tau + 1) + ...
% 				phase.Sigma22stressCoef2.*tau./(phase.Sigma22stressCoef4.*tau + 1).^2 + ...
% 				2.* phase.Sigma22stressCoef3.*tau.^2./(phase.Sigma22stressCoef4.*tau + 1).^3;
%             
%             sigma13 = phase.Sigma13stressCoef1./(phase.Sigma13stressCoef4.*tau + 1) + ...
% 				phase.Sigma13stressCoef2.*tau./(phase.Sigma13stressCoef4.*tau + 1).^2 + ...
% 				2.* phase.Sigma13stressCoef3.*tau.^2./(phase.Sigma13stressCoef4.*tau + 1).^3;
%             
%             sigma23 = phase.Sigma23stressCoef1./(phase.Sigma23stressCoef4.*tau + 1) + ...
% 				phase.Sigma23stressCoef2.*tau./(phase.Sigma23stressCoef4.*tau + 1).^2 + ...
% 				2.* phase.Sigma23stressCoef3.*tau.^2./(phase.Sigma23stressCoef4.*tau + 1).^3;
%             
%             eps_hkl = general.DEK_S2 .* (sind(spec.Psi)^2 .* (sigma11 .* cosd(spec.Phi).^2 + ...
%                         sigma22 .* sind(spec.Phi).^2) + sind(2 .* spec.Psi) .* (sigma13 .* cosd(spec.Phi) + ...
%                         sigma23 .* sind(spec.Phi))) + general.DEK_S1 .* (sigma11 + sigma22);
		end

		function obj = addFunctionParameters(obj, pc)

			obj.addParameter(pc, 'DEK_S1',...
				'Category', 'Material',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'DEK_S2',...
				'Category', 'Material',...
				'ParamSize', [NaN, 1],...
				'Constant', true,...
				'PhaseDep', true,...
				'SpecDep', true);
			obj.addParameter(pc, 'TwoTheta',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', false);
			obj.addParameter(pc, 'Psi',...
				'Category', 'Measurement',...
				'ParamSize', [1, 1],...
				'Constant', true,...
				'PhaseDep', false,...
				'SpecDep', true);
% 			obj.addParameter(pc, 'StressCoef',...
% 				'Category', 'Peaks',...
% 				'ParamSize', [4, 1],...
% 				'Constant', false,...
% 				'PhaseDep', true,...
% 				'SpecDep', false);
			obj.addParameter(pc, 'StressCoef1',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'StressCoef2',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'StressCoef3',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
			obj.addParameter(pc, 'StressCoef4',...
				'Category', 'Peaks',...
				'ParamSize', [1, 1],...
				'Constant', false,...
				'PhaseDep', true,...
				'SpecDep', false);
		end
	end
	
	methods (Access = protected)
		
		function obj = initSubFunctions(obj)
			
			obj.addSubFunction('Tau', 'rietveld.func.spec.diffpeaks.Tau', rietveld.func.spec.diffpeaks.Tau());
		end
	end
	
end



