classdef Polynomial < rietveld.func.spec.bkg.BkgInterface
	
	methods (Access = public)
		
		function Y = execute(obj, X, ~, ~, ~, spec)
			
			Y = polyval(spec.Background, X);
		end
		
		function obj = addFunctionParameters(obj, pc)
			
			obj.addParameter(pc, 'Background',...
				'Category', 'Background',...
				'ParamSize', [NaN, 1],...
				'Constant', false,...
				'PhaseDep', false,...
				'SpecDep', true);
            
%             obj.addParameter(pc, 'Background1',...
% 				'Category', 'Background',...
% 				'ParamSize', [NaN, 1],...
% 				'Constant', false,...
% 				'PhaseDep', false,...
% 				'SpecDep', true);
%             
%             obj.addParameter(pc, 'Background2',...
% 				'Category', 'Background',...
% 				'ParamSize', [NaN, 1],...
% 				'Constant', false,...
% 				'PhaseDep', false,...
% 				'SpecDep', true);
		end
	end
end

